### ISSUE TITLE
Dreamview can't display recorded data in Navigation mode

### ISSUE THREAD

**Issue by davidhopper2003** [ApolloAuto/apollo#7800] opened 2019-04-11 08:33 UTC
**Describe the bug**
A bag file (`csc.bag`) is recorded using the `rosbag` command and it can be displayed in Dreamview for Apollo 3.0 based on ROS. The bag file is converted to a record file (`csc.record`) using the command `rosbag_to_record csc.bag csc.record`. However, it can't be displayed in Dreamview for Apollo master branch (April 11, 2019, commit id `d4e48ae00f6555e2865ef8cff14f391f4c48372b`) based on CyberRT. 
All topics in the `csc.record` file can be displayed properly through the `cyber_monitor` tool.

**To Reproduce**
1. download the source code. 
``` bash
git pull --rebase upstream master
git reset --hard d4e48ae00f6555e2865ef8cff14f391f4c48372b
```
2. start and enter the docker. 
``` bash
bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh
```
3. build the apollo project. 
``` bash
bash apollo.sh build -j 8
```
4. convert the bag file to a record file. 
``` bash
rosbag_to_record data/bag/csc.bag data/bag/csc.record
```
5. modify the `modules/common/data/global_flagfile.txt` file as follows: 
  change
``` 
--use_navigation_mode=false
```
to  
``` 
--use_navigation_mode=true
```
and add a line:
``` 
--local_utm_zone_id=49
```

6. modify the `modules/localization/conf/localization.conf` file as follows: 
  change
``` 
--local_utm_zone_id=10
```
to  
``` 
--local_utm_zone_id=49
```

7. start Dreaview:
``` bash
bash scripts/bootstrap.sh
```

8. Replay the record file:
``` bash
cyber_recorder play -f data/bag/csc.record -l
```
**Expected behavior**
A planning trajectory is displayed in Dreamview.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: Chrome 68.0.3440.106 (Official Build) (64-bit)
 - Apollo Version: master branch (April 11, 2019, commit id `d4e48ae00f6555e2865ef8cff14f391f4c48372b`)

**Data file**
url: https://pan.baidu.com/s/1h9kG7qydpjO_WsIRirRYTw 
key: av3w

**Comment by vlin17** [comment] 2019-04-11 21:50
Hi @davidhopper2003 I can't reproduce the issue, I was able to see  trajectory in both the map and 3D scene. Can you check from cyber_monitor to see if the planning trajectory is sent?

![navigation](https://user-images.githubusercontent.com/2775888/55995279-efbce900-5c68-11e9-9473-bfa03a53fc40.png)

**Comment by davidhopper2003** [comment] 2019-04-12 01:52
@vlin17 Thank you. I guess the possible reason is as follows. I remember that the `csc.record` was generated with an old `rosbag_to_record` tool in January 2019. This file can be displayed properly in Dreamview for apollo 3.5 but can't be displayed for apollo master (April 11, 2019, commit id d4e48ae00f6555e2865ef8cff14f391f4c48372b).  Today, I deleted the old one and re-created a new one with the latest `rosbag_to_record` tool. The new record file can be displayed in Dreamview for apollo master (April 11, 2019, commit id d4e48ae00f6555e2865ef8cff14f391f4c48372b). Therefore, I doubt that the format of the record file has been changed. Please forgive me for any inconvenience.

**Comment by natashadsouza** [comment] 2019-04-12 20:57
@davidhopper2003 thanks for pointing it out. Currently closing this issue as it appears to be resolved.

**Closed by natashadsouza** 2019-04-12 20:57 UTC
Labels: Module: Simulation & Dreamview
