### ISSUE TITLE
rosnode list and rostopic list don't work in apollo2.5 release

### ISSUE THREAD

**Issue by HangHuang** [ApolloAuto/apollo#4124] opened 2018-05-09 13:12 UTC
hello:
I  finish all the instructions for the demo in  "https://github.com/ApolloAuto/apollo/tree/master/docs/demo_guide",
and the Dreamview can work properly：
![2018-05-09 21-36-20](https://user-images.githubusercontent.com/16897917/39817576-18a7cf20-53d1-11e8-8188-10ba6924e34d.png)

but when I execute “rostopic list” or "rosnode list",the terminal did not display any information：
![2018-05-09 21-29-08](https://user-images.githubusercontent.com/16897917/39817205-13fa07aa-53d0-11e8-94e1-4c16e0e75ef1.png)

The more information is as follows:

1）In the host terminal：

huanghang@dslab:~/apollo-downloads/apollo-2.5.0$ bash docker/scripts/release_start.sh
[sudo] huanghang 的密码： 
/apollo/data/core/core_%e.%p
Type 'y' or 'Y' to pull docker image from China mirror or any other key from US mirror.
y
release-x86_64-v2.0.1: Pulling from apolloauto/apollo
Digest: sha256:4c77b79bbf8ecbcf9b07a5180d7eb1ca9eb4b0f0984d7b61db597887e12f26fe
Status: Image is up to date for registry.docker-cn.com/apolloauto/apollo:release-x86_64-v2.0.1
modprobe: FATAL: Module nvidia not found in directory /lib/modules/4.13.0-39-generic
modprobe: FATAL: Module nvidia-uvm not found in directory /lib/modules/4.13.0-39-generic
af6555761a1a59c6efab55f29f0b28bf21b4a76c293954c1789ef1daa7adc8f8
Adding group `huanghang' (GID 1000) ...
Done.
Adding user `huanghang' ...
Adding new user `huanghang' (1000) with group `huanghang' ...
The home directory `/home/huanghang' already exists.  Not copying from `/etc/skel'.

Start roscore...
Started supervisord with release conf
Dreamview is running at http://localhost:8888
huanghang@dslab:~/apollo-downloads/apollo-2.5.0$ bash docker/scripts/release_into.sh
huanghang@in_release_docker:/apollo$ rosbag play docs/demo_guide/demo.bag --loop
/tmp/apollo-platform/ros/ros_comm/rosbag/src/player.cpp:125 Player::publish() [ INFO] [1525870513.629214485]: Opening docs/demo_guide/demo.bag

Waiting 0.2 seconds after advertising topics... done.

Hit space to toggle paused, or 's' to step.
 [RUNNING]  Bag Time: 1497125279.036971   Duration: 9.894491 / 38.393816

2）In another terminal：
 huanghang@dslab:~/apollo-downloads/apollo-2.5.0$ bash docker/scripts/release_into.sh 
huanghang@in_release_docker:/apollo$ rosnode list
ERROR: Unable to communicate with master!
huanghang@in_release_docker:/apollo$ roscore &
[1] 569
huanghang@in_release_docker:/apollo$ ... logging to /home/huanghang/.ros/log/958ee95e-5388-11e8-8e29-107b444d766c/roslaunch-in_release_docker-569.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://in_release_docker:40763/
ros_comm version 1.11.21
SUMARY
PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES

auto-starting new master
process[master]: started with pid [584]
ROS_MASTER_URI=http://in_release_docker:11311/

setting /run_id to 958ee95e-5388-11e8-8e29-107b444d766c
process[rosout-1]: started with pid [601]
started core service [/rosout]

huanghang@in_release_docker:/apollo$ rostopic list

huanghang@in_release_docker:/apollo$ rosnode list 

huanghang@in_release_docker:/apollo$ bash scripts/env.sh >& env.txt
huanghang@in_release_docker:/apollo$ cat env.txt 
in_release_docker
+ echo 'Inside docker'
Inside docker
+ uname -a
Linux in_release_docker 4.13.0-39-generic #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:10 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
+ pip list
actionlib (1.11.5)
argparse (1.2.1)
bondpy (1.7.19)
camera-calibration-parsers (1.11.12)
catkin (0.6.19)
catkin-pkg (0.3.6)
certifi (2017.7.27.1)
chardet (3.0.4)
click (6.7)
colorama (0.2.5)
cv-bridge (1.11.15)
decorator (3.4.0)
docutils (0.14)
dynamic-reconfigure (1.5.48)
enum-compat (0.0.2)
enum34 (1.1.6)
eventlet (0.21.0)
Flask (0.12.2)
Flask-Cors (3.0.3)
Flask-SocketIO (2.9.2)
gencpp (0.5.5)
genlisp (0.4.15)
genmsg (0.5.8)
genpy (0.5.10)
gevent (1.2.2)
glog (0.3.1)
google-apputils (0.4.2)
greenlet (0.4.12)
html5lib (0.999)
idna (2.6)
image-geometry (1.11.15)
itsdangerous (0.24)
Jinja2 (2.9.6)
MarkupSafe (1.0)
matplotlib (1.3.1)
meld3 (1.0.2)
message-filters (1.11.21)
numpy (1.8.2)
Pillow (2.3.0)
pip (1.5.4)
pluginlib (1.10.5)
plyvel (0.9)
protobuf (3.1.0)
pycurl (7.19.3)
pyparsing (2.0.1)
pyproj (1.9.5.1)
python-apt (0.9.3.5ubuntu2)
python-dateutil (1.5)
python-engineio (1.7.0)
python-gflags (3.1.1)
python-socketio (1.8.0)
pytz (2012c)
PyYAML (3.12)
requests (2.18.4)
rosbag (1.11.21)
rosboost-cfg (1.11.14)
rosclean (1.11.14)
roscreate (1.11.14)
rosgraph (1.11.21)
roslaunch (1.11.21)
roslib (1.11.14)
roslz4 (1.11.21)
rosmake (1.11.14)
rosmaster (1.11.21)
rosmsg (1.11.21)
rosnode (1.11.21)
rosparam (1.11.21)
rospbconvertor (1.0.0)
rospkg (1.1.2)
rospy (1.11.21)
rosservice (1.11.21)
rostest (1.11.21)
rostopic (1.11.21)
rosunit (1.11.14)
roswtf (1.11.21)
scipy (0.13.3)
sensor-msgs (1.11.9)
setuptools (3.3)
Shapely (1.6.2.post1)
simplejson (3.11.1)
six (1.5.2)
smclib (1.7.19)
sound-play (0.2.12)
supervisor (3.3.3)
tf (1.11.8)
tf-conversions (1.11.8)
tf2-geometry-msgs (0.5.13)
tf2-kdl (0.5.13)
tf2-py (0.5.13)
tf2-ros (0.5.13)
tf2-sensor-msgs (0.5.13)
urllib3 (1.22)
Werkzeug (0.12.2)
wheel (0.24.0)
wsgiref (0.1.2)
+ echo -----------env---------------
-----------env---------------
+ env
CPLUS_INCLUDE_PATH=/usr/local/cuda-8.0/include:
HOSTNAME=in_release_docker
TERM=xterm
ROS_ROOT=/apollo/ros/share/ros
ROS_PACKAGE_PATH=/apollo/ros/share:/apollo/ros/stacks
ROS_MASTER_URI=http://localhost:11311
APOLLO_BIN_PREFIX=/apollo
USER=huanghang
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64:/apollo/ros/lib:/apollo/lib:/home/caros/secure_upgrade/depend_lib
APOLLO_IN_DOCKER=true
CPATH=/apollo/ros/include
PATH=/usr/local/cuda-8.0/bin:/apollo/ros/bin:/apollo/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ROS_DOMAIN_ID=61132477
DOCKER_GRP=huanghang
C_INCLUDE_PATH=/usr/local/cuda-8.0/include:
PWD=/apollo
ROSCONSOLE_FORMAT=${file}:${line} ${function}() [${severity}] [${time}]: ${message}
DOCKER_GRP_ID=1000
ROSLISP_PACKAGE_DIRECTORIES=
DOCKER_USER_ID=1000
DOCKER_USER=huanghang
HOME=/home/huanghang
SHLVL=2
ROS_DISTRO=indigo
PYTHONPATH=/usr/local/lib/python2.7/dist-packages:/apollo/lib:/apollo/modules/tools:/apollo/lib:/apollo/ros/lib/python2.7/dist-packages
RELEASE_DOCKER=1
LESSOPEN=| /usr/bin/lesspipe %s
PKG_CONFIG_PATH=/apollo/ros/lib/pkgconfig
DOCKER_IMG=apolloauto/apollo:release-x86_64-v2.0.1
DISPLAY=:0
CMAKE_PREFIX_PATH=/apollo/ros
LESSCLOSE=/usr/bin/lesspipe %s %s
ROS_ETC_DIR=/apollo/ros/etc/ros
APOLLO_BASE_SOURCED=1
_=/usr/bin/env
huanghang@in_release_docker:/apollo$ 

3）another terminal：
![2018-05-09 21-27-12](https://user-images.githubusercontent.com/16897917/39817097-c9b28190-53cf-11e8-8e39-cea827a1ed67.png)

what‘s wrong in my steps？Sincerely hope to get some help！

------------------
祝身体健康，工作愉快！

H.Huang (黄航)  2846440252@qq.com
Distributed & Embedded System Lab
School of Information Science and Engineering,Lanzhou University
South Tianshui Road 222, Lanzhou City, 730000

**Comment by HangHuang** [comment] 2018-05-11 01:46
I found the reason: 
my Ubuntu version is 16.04 in my host. When I changed to 14.04, the problem was solved.
thanks！

**Comment by Zhenni17** [comment] 2018-05-12 02:08
Hi @HangHuang , I am glad that the issue is resolved. I will close the issue for now, and please feel free to open an new issue if you have additional question!

Best,
Zhenni

**Closed by Zhenni17** 2018-05-12 02:08 UTC
Labels: Module: ROS, Type: Question
