### ISSUE TITLE
Can't display the trajectory of the car in dreamview I record by myself

### ISSUE THREAD

**Issue by xinwf** [ApolloAuto/apollo#5242] opened 2018-08-04 15:24 UTC
It can run normally in terminal, but no response in dreamview
![screenshot from 2018-08-04 22-13-01](https://user-images.githubusercontent.com/41889613/43677957-540973a6-983d-11e8-9b24-6202287c434a.png)

the bag info
![screenshot from 2018-08-04 22-12-28](https://user-images.githubusercontent.com/41889613/43677966-77492e38-983d-11e8-9ba2-df88f87a299d.png)

**Comment by gladijos** [comment] 2018-08-07 06:55
What mode do you use in dreamview? Try change from one to another. A month ago I have issue then for displaying lanes and planning trajectory I have to switch on simcontrol and switch of it.
I think it is wide spread problem of understanding what are we needed to visualize in dreamview different data?

**Comment by xinwf** [comment] 2018-08-07 09:13
Sorry, I was puzzled by your explanation.  I think the replay process doesn't have a relation with other things. When we run the command `rosbag play docs/demo_guide/demo_2.0.bag`, we don't need to set anything, the dreamview can display the offline simulation of the car. I think maybe the problem is that I only record two topics, when I use the command `rosbag info docs/demo_guide/demo_2.0.bag`, there are many topics' data in it, but when I try to record a number of topics which have data for publishing, it only can record 4 topics, other topics can't be recorded, neither the official script nor the script written by myself is not useful.

**Comment by vlin17** [comment] 2018-08-10 23:16
@xinwf  dreamview displays trajectory in the /apollo/planning topic. Can you check if the planning topic is recorded?  If recording topic is the cause, can you share your recording command? In addition, have you try recording with ./scripts/record_bag.sh?

**Comment by xinwf** [comment] 2018-08-11 02:13
@vlin17 ，thank you for your reply, there is no planning topic in the bag file, I only can record and get four topics info even I use the official scripts(record_bag.sh), I don't know why it happens. I have modified another calibration scripts to record topics' data as following
```bash
#!/usr/bin/env bash

source /apollo/scripts/apollo_base.sh
rosbag record -O trajectory_data_for_replay.bag \
    /apollo/canbus/chassis \
    /apollo/control \
    /apollo/localization/pose \
    /apollo/planning \
    /apollo/sensor/conti_radar \
    /apollo/sensor/gnss/best_pose \
    /apollo/sensor/gnss/corrected_imu \
    /apollo/sensor/gnss/imu \
    /apollo/sensor/gnss/gnss_status \
    /apollo/sensor/gnss/ins_stat \
    /apollo/sensor/gnss/odometry \
    /apollo/sensor/gnss/rtk_eph \
    /apollo/sensor/gnss/rtk_obs \
    /tf
sleep 3s
mv trajectory_data_for_replay.bag /apollo/data/bag/
```
It also doesn't work, after recording, I get four topics' data as following:
```
/apollo/sensor/gnss/best_pose 
/apollo/sensor/gnss/gnss_status
/apollo/sensor/gnss/odometry
/tf
```
I really don't know why it happens.

**Comment by gladijos** [comment] 2018-08-13 06:33
@xinwf  Can you check topiclist when you are recording data. May be you are not producing this type of data?
Do you use apollo's planning module or your own for producing planning data?
I don't see any planning data in screen of your bag-file info.

**Comment by xinwf** [comment] 2018-08-13 07:31
@gladijos ，do you mean I need to turn on the planning module when I begin to record trajectory data?
I haven't enabled the planning module in previous recording process. I will have a try. And what's more, does the `planning ` topic can produce data after I turn on it or its data depends on other topics'?

**Comment by xinwf** [comment] 2018-08-13 07:34
@gladijos @vlin17 , after I start the dreamview, the planning topic is in the topic list, but no data output, do I need to enable the planning module, and then it will produce data?

**Comment by vlin17** [comment] 2018-08-13 18:21
@xinwf Yes, if your bag doesn't have planning data, please turn on the planning module. You can use the diagnostics tool (by running "bash ./scripts/diagnostics.sh") to verify if there is output protobuf messages from planning.

**Comment by xinwf** [comment] 2018-08-14 10:28
@vlin17  Thank you for your reply, I have tried that, it does work, but another problem is still in there, the scripts(I write by myself or the official) can't record the data of planning topic and other topics, it only can record four topics, it is very strange. The script I used to record data has been given in aforementioned reply. Can you give me some advice?

**Comment by natashadsouza** [comment] 2018-09-12 23:18
Currently closing this issue as it appears to be resolved. @xinwf if you have any additional questions, feel free to reopen this issue. Thanks!

**Closed by natashadsouza** 2018-09-12 23:18 UTC
Labels: Module: Simulation & Dreamview, Type: Help wanted
