### ISSUE TITLE
Cyber Reader Doesn't Clear Callback Before Shutdown

### ISSUE THREAD

**Issue by Fla3inH0tCheet0s** [ApolloAuto/apollo#9307] opened 2019-08-05 19:17 UTC
**Describe the bug**
`Cyber::Reader` should wait for all callbacks to return before returning from the destructor or shutdown method. Without doing so there is a risk that the callback will access deallocated data. This bug is more obvious when using member variables in longer callbacks and shutting down.

A workaround is to wrap the readers in a class. Then, in the wrapper class's destructor call all readers shutdown method and sleep for about 10 milliseconds for short callbacks or however long the slowest callback will take with some small extra buffer time.

**To Reproduce**
Add
```
TEST(WriterReaderTest, reader_takes_time) {
  std::atomic<bool> finished_callback{false};
  {
    proto::RoleAttributes attr;
    attr.set_node_name("writer");
    attr.set_channel_name("reader_takes_time");
    auto channel_id = common::GlobalData::RegisterChannel(attr.channel_name());
    attr.set_channel_id(channel_id);

    Writer<proto::UnitTest> writer(attr);
    EXPECT_TRUE(writer.Init());

    attr.set_node_name("reader_a");
    Reader<proto::UnitTest> reader_a(
        attr, [&finished_callback](const std::shared_ptr<proto::UnitTest>&) {
          std::this_thread::sleep_for(std::chrono::milliseconds(1000));
          finished_callback = true;
        });
    EXPECT_TRUE(reader_a.Init());

    auto msg = std::make_shared<proto::UnitTest>();
    msg->set_class_name("WriterReaderTest");
    msg->set_case_name("messaging");

    writer.Write(msg);
    std::this_thread::sleep_for(std::chrono::milliseconds(500));

    EXPECT_TRUE(writer.HasReader());
    EXPECT_TRUE(reader_a.HasWriter());
  }

  EXPECT_TRUE(finished_callback);
}
```
to `cyber/node/writer_reader_test.cc`
Run
```
bazel test //cyber/node:writer_reader_test
```

**Expected behavior**
Cyber reader should only follow RAII and only access the data that is in scope between when it is constructed and destructed.

**Desktop (please complete the following 
 - Version 5fa358fc66e54ab7f9f56594e2164f63872a5528

**Comment by fengqikai1414** [comment] 2019-08-06 09:07
Hi @Fla3inH0tCheet0s ，when a Reader is destructed, the topology manager is notified to de-register the reader-related information, and then the scheduler deletes the callback registered by the Reader. If the callback is being executed, it needs to wait for its execution to complete.

> Cyber reader should only follow RAII and only access the data that is in scope between when it is constructed and destructed.

Callbacks are inherently an asynchronous process that does not require follow RAII here.

> Without doing so there is a risk that the callback will access deallocated data. 

The root cause of this risk is that the callback function uses a lambda, and the lambda capture the variable by reference.

So I think this is not a serious problem.

**Comment by Fla3inH0tCheet0s** [comment] 2019-08-06 18:19
> If the callback is being executed, it needs to wait for its execution to complete.

How? The callback may be queued up so any non static or non global variable accessed would be invalid. It seems better to define this in the cyber library.

> The root cause of this risk is that the callback function uses a lambda, and the lambda capture the variable by reference.

This is an isolated test. For a more real example, think of the planning component. If the component goes out of scope both the readers and the member variable `local_view_` go out of scope. The readers are shutdown, but `Proc` could still run. At this point the member variable `local_view_` could be written.

> So I think this is not a serious problem.

This limitation affects all components that use member variables in `Proc` on shutdown. It's undefined behavior on shut down. For the most part, the O.S. will clean the process up and the other cyber components should timeout.

**Comment by Fla3inH0tCheet0s** [comment] 2019-08-07 20:42
> For a more real example, think of the planning component. If the component goes out of scope both the readers and the member variable local_view_ go out of scope. The readers are shutdown, but Proc could still run. At this point the member variable local_view_ could be written.

I did some more testing on running `mainboard -d modules/planning/dag/planning.dag`. The original issue doesn't affect components started with mainboard. I'm still getting my head around the structure. It appears that Mainboard controller shutsdown all its components. Then, Cyber's [ExitHandle](https://github.com/ApolloAuto/apollo/blob/master/cyber/init.cc#L85) stops all the tasks. Finally, the [static Component](https://github.com/ApolloAuto/apollo/blob/master/cyber/class_loader/utility/class_loader_utility.cc#L37) is destructed.

There are a few other shutdown issues with `mainboard -d modules/planning/dag/planning.dag`. They should be in another issue or other PR.

For my use case, I would like to encapsulate a class that uses a reader without shutting down all of cyber. I figure that the `cyber::Reader` destructor should return at the right time so that the other variables can go out of scope safely.

**Comment by fengqikai1414** [comment] 2019-08-08 02:23
@Fla3inH0tCheet0s ,
> How? The callback may be queued up so any non static or non global variable accessed would be invalid. It seems better to define this in the cyber library.

Please see [here](https://github.com/ApolloAuto/apollo/blob/136b0d50260d65eb11997a318d0fd6abbd1efd19/cyber/node/reader.h#L302) and [here](url). If the callback is executing, `cr->Acquire()` will return false, the thread will wait in a loop until the callback execution is complete, then `cr->Acquire()` returns true, and then the callback is removed from the task queue.we just merged from internal development version. 

> For a more real example, think of the planning component. If the component goes out of scope both the readers and the member variable local_view_ go out of scope. The readers are shutdown, but Proc could still run. At this point the member variable local_view_ could be written.

The life cycle of all components is controlled by the mainboard. Before the component is destroyed, all Readers will be shut down first, so that Proc will be executed before the component is destroyed, so the risk mentioned above does not exist.

Sorry for the implementation of the feature in the current open source version has a bug we have fixed in the internal development version, and just synced to github, please see #9332 .

**Comment by Fla3inH0tCheet0s** [comment] 2019-08-08 23:09
I tried out https://github.com/ApolloAuto/apollo/pull/9332 on the test. It passed. Thanks!

**Closed** 2019-08-09 01:44 UTC
Labels: Module:Cyber, Type: Help wanted
