### ISSUE TITLE
Segmentation fault when building Apollo

### ISSUE THREAD

**Issue by kwailamchan** [ApolloAuto/apollo#3605] opened 2018-03-27 20:34 UTC
When building with `./apollo.sh build_no_perception dbg`, segmentation fault error occurred on

- OS: Ubuntu 18.04
- Docker: docker for artful
- Apollo: latest master branch

```
[2,316 / 2,322] 3 actions running
ERROR: /apollo/modules/common/time/BUILD:23:1: C++ compilation of rule '//modules/common/time:time_test' failed (Exit 1)
In file included from /usr/include/c++/4.8/string:52:0,
                 from /usr/include/c++/4.8/stdexcept:39,
                 from ./modules/common/time/time.h:29,
                 from modules/common/time/time_test.cc:17:
/usr/include/c++/4.8/bits/basic_string.h: In instantiation of 'class std::basic_string<wchar_t>':
/usr/include/c++/4.8/bits/basic_string.h:2927:68:   required from here
/usr/include/c++/4.8/bits/basic_string.h:1810:7: internal compiler error: Segmentation fault
       data() const _GLIBCXX_NOEXCEPT
       ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
The bug is not reproducible, so it is likely a hardware or OS problem.
```

**Comment by lianglia-apollo** [comment] 2018-03-27 23:10
FYI, I was not able to reproduce this bug on our development PC. It might require more time to debug.

**Comment by kwailamchan** [comment] 2018-03-28 02:09
@lianglia-apollo Thanks for your response.

**Dev Version**
I am wondering the error occurred might be because of out of memory?
Deployed Apollo with `dev_start` and `dev_into`, and built the platform inside on Ubuntu/Mac, the same error was shown. So, the process steps were incorrect?

**Release Version**
Deployed Apollo with `release_start`, the dreamviewer (localhost:8888) worked well, while running the demo inside, everything looked good.

**Comment by kwailamchan** [comment] 2018-03-29 10:10
@lianglia-apollo 

Tried to build from source, whatever on Ubuntu 16.04 or Ubuntu 18.04, ran `./apollo.sh build_no_perception dbg`, the same error occurred. How should I fix it? Thanks.

```
Extracting Bazel installation...
..........................
ERROR: /home/apollo/.cache/bazel/_bazel_apollo/f3ef0319ff1a778706604ee3e7ea315e/external/com_google_protobuf/BUILD:441:1: Traceback (most recent call last):
	File "/home/apollo/.cache/bazel/_bazel_apollo/f3ef0319ff1a778706604ee3e7ea315e/external/com_google_protobuf/BUILD", line 441
		cc_proto_library(name = "cc_test_protos", srcs = (L...), <4 more arguments>)
	File "/home/apollo/.cache/bazel/_bazel_apollo/f3ef0319ff1a778706604ee3e7ea315e/external/com_google_protobuf/protobuf.bzl", line 247, in cc_proto_library
		cc_libs += [default_runtime]
trying to mutate a frozen object
ERROR: /home/apollo/.cache/bazel/_bazel_apollo/f3ef0319ff1a778706604ee3e7ea315e/external/com_google_protobuf/BUILD:742:1: Traceback (most recent call last):
	File "/home/apollo/.cache/bazel/_bazel_apollo/f3ef0319ff1a778706604ee3e7ea315e/external/com_google_protobuf/BUILD", line 742
		py_proto_library(name = "python_specific_test_pro...", <6 more arguments>)
	File "/home/apollo/.cache/bazel/_bazel_apollo/f3ef0319ff1a778706604ee3e7ea315e/external/com_google_protobuf/protobuf.bzl", line 373, in py_proto_library
		py_libs += [default_runtime]
trying to mutate a frozen object
```

**Comment by slivingston** [comment] 2018-03-31 00:57
I am able to reproduce the error on Ubuntu 16.04 with respect to current tip of `master` (f03e3af332666c3f5253526f2ebdbf73ccfebda8).

**Comment by slivingston** [comment] 2018-03-31 05:28
@kwailamchan did you try to update the version of Protobuf that is used?

```diff
diff --git a/WORKSPACE.in b/WORKSPACE.in
index 4f28a02..c64d46f 100644
--- a/WORKSPACE.in
+++ b/WORKSPACE.in
@@ -186,6 +186,6 @@ new_http_archive(
 #protobuf 3.3
 http_archive(
     name = "com_google_protobuf",
-    strip_prefix = "protobuf-3.3.0",
-    url = "https://github.com/google/protobuf/releases/download/v3.3.0/protobuf-cpp-3.3.0.tar.gz",
+    strip_prefix = "protobuf-3.5.1",
+    url = "https://github.com/google/protobuf/releases/download/v3.5.1/protobuf-cpp-3.5.1.tar.gz",
 )
```

**Comment by slivingston** [comment] 2018-03-31 05:35
I suggest so because Protobuf 3.3.0 includes bugs with respect to the current Bazel version. E.g., for C++ it was fixed at google/protobuf@4fc93044a5de018527ec027dbee6a882012e0d9d after release of v3.3.0

**Comment by kwailamchan** [comment] 2018-03-31 16:39
@slivingston Thank you for the detailed explanation.

I updated protobuf from 3.3.0 to 3.5.1, the error message was gone, however, another one is flagged:

```
ERROR: /home/apollo/Studio/apollo-r2.0.0/modules/common/transform_listener/BUILD:5:1: no such package '@ros//': Expected directory at /home/tmp/ros but it does not exist. and referenced by '//modules/common/transform_listener:transform_listener'
ERROR: Analysis of target '//modules/common/transform_listener:transform_listener' failed; build aborted: no such package '@ros//': Expected directory at /home/tmp/ros but it does not exist.
INFO: Elapsed time: 7.929s
FAILED: Build did NOT complete successfully (10 packages loaded)
    currently loading: @bazel_tools//tools/test ... (2 packages)
============================
[ERROR] Build failed!
[INFO] Took 3528 seconds
============================
```

Then I created the folder ``mkdir -p /home/tmp/ros``, re-ran ``./apollo.sh build_no_perception dbg``, another error is flagged:

```
[INFO] Start building, please wait ...
[INFO] Skip building perception module!
ERROR: query interrupted
============================
[ERROR] Build failed!
[INFO] Took 729 seconds
============================
```

Please note that I installed ros by ``sudo apt-get install ros-kinetic-desktop-full`` before building Apollo, the installation path is ``/opt/ros``.

**Comment by slivingston** [comment] 2018-03-31 23:13
the error of /home/tmp/ros not found appears the same as that of #854

**Comment by slivingston** [comment] 2018-04-01 00:30
@kwailamchan is your goal to build from source outside of a Docker container?

I am trying to do so now. The [installation instructions in the root README](https://github.com/ApolloAuto/apollo/blob/b094cd655d61cb8b349d8c48b2c3b42e14ae2d3a/README.md#installation) recommend to use their Docker image, and the [Travis CI configuration for this repo](https://github.com/ApolloAuto/apollo/blob/b094cd655d61cb8b349d8c48b2c3b42e14ae2d3a/.travis.yml) uses their Docker image, so I hypothesize that building from source without their Docker image is not well tested.

**Comment by slivingston** [comment] 2018-04-01 00:41
I just discovered #2468 and #2737. We are all still waiting.

**Comment by kwailamchan** [comment] 2018-04-01 03:51
@slivingston Thanks for providing the resources.

I tried 3 ways to install Apollo:
- Docker release (os: ubuntu 14.04) on Ubuntu 18.04 -> OK;
- Docker dev (os: ubuntu 14.04) on Ubuntu 18.04 -> OK;
- Apollo source (os: ubuntu 16.04) on OSX Virtualbox -> a lot of steps and libraries are needed to be installed (not fully tested so far).

## Docker dev (os: ubuntu 14.04) on Ubuntu 18.04

Checked the protobuf version with ``protoc --version``, it was shown as `v3.3.0`.
Built with ``./apollo.sh build_no_perception dbg``, segmentation fault could be happened when building opencv2, boost, apollo modules etc, it could be happened on uncertain libs when buildinig the modules. 
Ignoring this error, re-typed ``./apollo.sh build_no_perception dbg``, again and again, finally built succeeded.

Typed ``scripts/bootstrap.sh``, dreamview worked well.
Tried the demo, demo_2.0 worked well.


## Apollo source (os: ubuntu 16.04) on OSX Virtualbox

It could be more confused on this installation:
- the [README](https://github.com/ApolloAuto/apollo/blob/master/README.md) indicated that it was tested on Ubuntu 16.04, whereas the ``apollo-kernel`` and ``apollo-platform`` are only supported on ros-indigo (that may be installed on Ubuntu 14.04);
- too much libs and packages have to be installed manually.

**Comment by natashadsouza** [comment] 2018-08-27 23:42
Closing this issue as there has been no communication in a while. Please let me know if you have additional questions.

**Closed by natashadsouza** 2018-08-27 23:42 UTC
Labels: Module: Build, Type: Help wanted
