### ISSUE TITLE
eigen error occurs when running apollo on arm64 ?

### ISSUE THREAD

**Issue by oska874** [ApolloAuto/apollo#11256] opened 2020-05-15 09:03 UTC
I'm running apollo 5.5 on arm64 platform. When velodyne driver run into here:
![image](https://user-images.githubusercontent.com/4536559/82030229-bb68f700-96ca-11ea-91f8-fcc54bd35a69.png)
It will show error of eigen:
![image](https://user-images.githubusercontent.com/4536559/82031927-1f8cba80-96cd-11ea-978c-6faa2dcdf49b.png)

The code of the error occured is in modules/drivers/velodyne/compensator/compensator.cc here,two vector multiply:
![image](https://user-images.githubusercontent.com/4536559/82029899-3aa9fb00-96ca-11ea-88cb-d9f1db6279d5.png)

How to solve this problem?

**Comment by jilinzhou** [comment] 2020-05-23 03:02
Create a small program just using eigen, run the same code piece, and figure out from there.

**Comment by storypku** [comment] 2020-07-08 14:07
> I'm running apollo 5.5 on arm64 platform. When velodyne driver run into here:
> ![image](https://user-images.githubusercontent.com/4536559/82030229-bb68f700-96ca-11ea-91f8-fcc54bd35a69.png)
> It will show error of eigen:
> ![image](https://user-images.githubusercontent.com/4536559/82031927-1f8cba80-96cd-11ea-978c-6faa2dcdf49b.png)
> 
> The code of the error occured is in modules/drivers/velodyne/compensator/compensator.cc here,two vector multiply:
> ![image](https://user-images.githubusercontent.com/4536559/82029899-3aa9fb00-96ca-11ea-88cb-d9f1db6279d5.png)
> 
> How to solve this problem?

This problem was caused by eigen alignment requirement which Apollo r5.5.0 doesn't address well.
See http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html .
It was fixed in Apollo master as of master 3711be4317

**Comment by michael4338** [comment] 2020-07-13 18:38
closing now, please try the solution above

**Closed by michael4338** 2020-07-13 18:38 UTC
Labels: Module: Driver
