### ISSUE TITLE
ModuleNotFoundError: No module named 'cyber.python';

### ISSUE THREAD

**Issue by guo-pu** [ApolloAuto/apollo#13495] opened 2021-03-01 10:26 UTC
**from cyber.python.cyber_py3 import cyber
**ModuleNotFoundError: No module named 'cyber.python'; 'cyber' is not a package

How to solve this problem？

**Comment by storypku** [comment] 2021-03-01 11:38
Duplicate of #13493 , will be closed.

**Closed by storypku** 2021-03-01 11:38 UTC
