### ISSUE TITLE
The valet parking in apollo 5.5 doesn't work

### ISSUE THREAD

**Issue by IDovgopolik** [ApolloAuto/apollo#14330] opened 2022-02-28 10:17 UTC
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ububtu 20.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.5

Hello to all! I successfully run the valet parking in apollo 6.0 via mock_routing and end_way_point, but when I tried to do this in apollo 5.5 it's failed. I see in cyber_monitor that the routing_request doesn't have info about parking which I send by mock_routing and end_way_point. I'm using the AutonomouStuff map and there are my mock_routing:
![mock_routing](https://user-images.githubusercontent.com/63422436/155963815-19b81338-dc85-4c53-a754-cdc0147c0fcf.png)
and end_way_point:
![end_way](https://user-images.githubusercontent.com/63422436/155964030-f329aade-3550-45eb-865a-37cca75429c3.png)
Can you, please, tell me what's wrong?

P.S. Also I have a bug with dreamview in Sim_control mode. After I send the routing_request manually via mock_routing or end_way_point, 
indicators and pnc monitors show that auto starts movement, but visualization shows that it's in start position. It shows the right position after the auto is near to final position. I'm not sure that this bug is a part of main issue problem, but just in case tell about it.

**Comment by daohu527** [comment] 2022-03-01 00:33
So what is your problem then, what error message does it give?

**Comment by IDovgopolik** [comment] 2022-03-01 09:37
@daohu527, after I run mock_routing:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/63422436/156140731-37374f36-6666-463f-9466-057304a436f2.gif)
The problem is the valet parking doesn't work. The same waypoints and parking_info work right for apollo 6.0. I run routing and planning using mainboard -d, and there are no errors.

**Comment by daohu527** [comment] 2022-03-01 13:06
According to the previous issue https://github.com/ApolloAuto/apollo/issues/13950, 5.5 may not work. If there is no error, we may first need to confirm whether the parking is triggered

**Comment by IDovgopolik** [comment] 2022-03-01 16:20
I found why the valet parking didn't start. The reason is different types of parking_info description. I don't know why, the routing.proto files are the same in apollo 5.5 and apollo 6.0. 
![Screenshot from 2022-03-01 18-51-57](https://user-images.githubusercontent.com/63422436/156202211-575e272b-5969-44de-9166-119efc19b8e3.png)
In file end_way_point.txt (which is in folder with map): green rectangular is a description which works in apollo 6.0, red rectangular - apollo 5.5. Now the valet parking starts, but on the stage VALET_PARKING_PARKING it's failed:
![Screenshot from 2022-03-01 19-13-54](https://user-images.githubusercontent.com/63422436/156206254-8e24080d-ec73-4312-b5fd-f6877baf6fd4.png)
Planning module is crashed. The error message:
`E0301 18:47:23.595955 312934 stage.cc:130] [planning]Failed to run tasks[OPEN_SPACE_TRAJECTORY_PROVIDER], Error message: State warm start problem failed to solve
E0301 18:47:23.595996 312934 stage_parking.cc:34] [planning]StageParking planning error
E0301 18:47:23.596010 312934 scenario.cc:79] [planning]Stage 'VALET_PARKING_PARKING' returns error
`

**Comment by chenxiaoying21** [comment] 2022-07-29 08:47
Hi, IDovgopolik, since the issue is overdue and will not reproduce in 6.0, I will close it now.

**Closed by chenxiaoying21** 2022-07-29 08:47 UTC
Labels: Module: Planning
