### ISSUE TITLE
Why path_out_lane_cost is not used?

### ISSUE THREAD

**Issue by KevinYuk** [ApolloAuto/apollo#9218] opened 2019-07-24 07:18 UTC
path_out_lane_cost is not used when calculate path cost, and this would cause the ADC slowly come back to lane after it out of lane.

 ```
   dp_poly_path_config {
        sample_points_num_each_level: 7
        step_length_max: 40.0
        step_length_min: 20.0
        lateral_sample_offset: 0.5
        lateral_adjust_coeff: 0.5
        eval_time_interval: 0.1
        path_resolution: 1.0
        obstacle_ignore_distance: 20.0
        obstacle_collision_distance: 0.5
        obstacle_risk_distance: 2.0
        obstacle_collision_cost: 1e8
        path_l_cost: 6.5
        path_dl_cost: 8e3
        path_ddl_cost: 5e1
        path_l_cost_param_l0: 1.50
        path_l_cost_param_b: 0.40
        path_l_cost_param_k: 1.5
        path_out_lane_cost: 1e8
        path_end_l_cost: 1.0e4
        sidepass_distance: 2.8
        navigator_sample_num_each_level: 3
    }
```

```
ComparableCost TrajectoryCost::CalculatePathCost(
    const QuinticPolynomialCurve1d &curve, const float start_s,
    const float end_s, const uint32_t curr_level, const uint32_t total_level) {
  ComparableCost cost;
  float path_cost = 0.0;
  std::function<float(const float)> quasi_softmax = [this](const float x) {
    const float l0 = this->config_.path_l_cost_param_l0();
    const float b = this->config_.path_l_cost_param_b();
    const float k = this->config_.path_l_cost_param_k();
    return (b + std::exp(-k * (x - l0))) / (1.0 + std::exp(-k * (x - l0)));
  };

  const auto &vehicle_config =
      common::VehicleConfigHelper::instance()->GetConfig();
  const float width = vehicle_config.vehicle_param().width();

  for (float curve_s = 0.0; curve_s < (end_s - start_s);
       curve_s += config_.path_resolution()) {
    const float l = curve.Evaluate(0, curve_s);

    path_cost += l * l * config_.path_l_cost() * quasi_softmax(std::fabs(l));

    double left_width = 0.0;
    double right_width = 0.0;
    reference_line_->GetLaneWidth(curve_s + start_s, &left_width, &right_width);

    constexpr float kBuff = 0.2;
    if (!is_change_lane_path_ && (l + width / 2.0 + kBuff > left_width ||
                                  l - width / 2.0 - kBuff < -right_width)) {
      cost.cost_items[ComparableCost::OUT_OF_BOUNDARY] = true;
    }

    const float dl = std::fabs(curve.Evaluate(1, curve_s));
    path_cost += dl * dl * config_.path_dl_cost();

    const float ddl = std::fabs(curve.Evaluate(2, curve_s));
    path_cost += ddl * ddl * config_.path_ddl_cost();
  }
  path_cost *= config_.path_resolution();

  if (curr_level == total_level) {
    const float end_l = curve.Evaluate(0, end_s - start_s);
    path_cost +=
        std::sqrt(end_l - init_sl_point_.l() / 2.0) * config_.path_end_l_cost();
  }
  cost.smoothness_cost = path_cost;
  return cost;
}
```

**Comment by jmtao** [comment] 2019-07-25 17:52
@KevinYuk the value of "path_out_lane_cost" is huge and it was intended to *force* adc to keep in-lane.  But that's not always what we really want, e.g when adc side-pass obstacles or change lanes...
and "path_l_cost" can help *keep* adc in lane. 
BTW, in Apollo 5.0, we are not using dp_poly_path_optimizer any more.

**Comment by jmtao** [comment] 2019-07-30 17:11
Hi @KevinYuk , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!

**Closed by jmtao** 2019-07-30 17:11 UTC
Labels: Module: Planning, Type: Help wanted

**Comment by KevinYuk** [comment] 2019-07-31 01:04
@jmtao OK. Thanks for your quick feedback.

**Comment by HandsomeDragon3** [comment] 2021-01-12 01:59
Thank you, I cannot find dp_poly_path_config.proto in path  #include "modules/planning/proto/dp_poly_path_config.pb.h", which is needed  by tasks/optimizer/road_graph/trajectory_cost.h

**Comment by HandsomeDragon3** [comment] 2021-01-12 02:06
Is it for the reason that "in Apollo 5.0, we are not using dp_poly_path_optimizer any more."?
