### ISSUE TITLE
Cannot execute the autonomous driving

### ISSUE THREAD

**Issue by kdheejb7** [ApolloAuto/apollo#11847] opened 2020-07-18 13:30 UTC
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0(pre6)

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):
I have finished the setup and turning on the several controller.
However, I cannot execute the autonomous driving of my vehicle.
![image](https://user-images.githubusercontent.com/39160667/87853512-918bb500-c945-11ea-885c-9a7f7ee45086.png)

I read the same issue (#10882), the solution that was written is manually pusing the up button.
but, is didn't work for me.
Please give me some solution to autonomous driving :( 

Thank you

**Comment by vlin17** [comment] 2020-07-20 18:23
Are you trying to run Apollo with LGSVL?
Also, please check log under /apollo/data/log to see if there's any error.

**Comment by kdheejb7** [comment] 2020-07-21 01:01
> Are you trying to run Apollo with LGSVL?
Yes, I'm running Apollo with LGSVL.
> Also, please check log under /apollo/data/log to see if there's any error.
This is my routing.log with error
![image](https://user-images.githubusercontent.com/39160667/88000636-1a1e7700-cb39-11ea-974b-7bb2e09c921e.png)


Thank you.

**Comment by vlin17** [comment] 2020-07-21 02:59
As the route has been created (the red line in Dreamview), the error to check isn't from the routing module. Planning is a good one to check.

**Comment by kdheejb7** [comment] 2020-07-21 03:20
> As the route has been created (the red line in Dreamview), the error to check isn't from the routing module. Planning is a good one to check.

This is routing.log.INFO.
Is there anything about routing log??

**Comment by vlin17** [comment] 2020-07-21 03:26
Do you see any other log files other than routing.log.INFO? If so, please check planning.INFO as the problem is most likely from planning module.

**Comment by kdheejb7** [comment] 2020-07-21 03:32
> Do you see any other log files other than routing.log.INFO? If so, please check planning.INFO as the problem is most likely from planning module.

![image](https://user-images.githubusercontent.com/39160667/88009679-0af5f400-cb4e-11ea-96b3-9cc2f1e0b027.png)

This is planning module error.
Hmm.. is this routing error or planning error?

Thanks!

**Comment by vlin17** [comment] 2020-07-22 03:25
@ycool  We see routing is generated, but planning  says "Routing is not ready".  Thoughts about what can go wrong here?

**Comment by jmtao** [comment] 2020-08-06 17:18
@kdheejb7 The error message from planning module indicates the planning hasn't received routing. 
How did you create routing? Was planning started and running fine before the routing was generated?

**Comment by jmtao** [comment] 2020-08-31 22:23
Hi @kdheejb7 hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!

**Closed by jmtao** 2020-08-31 22:23 UTC
Labels: Module: Simulation & Dreamview
