### ISSUE TITLE
Question about the build in the VSCode

### ISSUE THREAD

**Issue by CCodie** [ApolloAuto/apollo#6335] opened 2018-12-31 05:27 UTC
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 14.04
- **Apollo installed from (source or binary)**: From source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: Version 3.0

### Issue:
Hi, guys. I want to debug Apollo project with VSCode such as analyzing flow of module's algorithm.
I had successfully done with 'build the Apollo Project in VSCode' as instructed in documents 
[how to build and release](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md#build_in_vscode) and [how to build and debug using vscode](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_debug_using_vscode.md).

**Q. I wonder that 'build and run in PC using terminal' and 'build in VSCode' are different things ?**
I already built Apollo Project in my PC and ran Dreamview. And then, I newly build Apollo Project in VSCode. Are they independent? Build in VSCode doesn't affect previously built Apollo Project in my PC ?

Thanks.

**Comment by kk2491** [comment] 2018-12-31 09:11
As per my understanding and experiments, you can do the below 2 approaches.

1) Build Apollo in terminal, run dreamview then debug using VS code. 
2) Or build apollo using VS code and debug.

The only difference is that, when you build code using VS code along with the build, dev_start.sh would be executed. You can check ```tasks.json``` file.

```
    "tasks": [
        {
            "label": "build the appolo project",
            "type": "shell",
            // you can change the "build" option to others acording to the "apollo.sh" file
            "command": "bash apollo_docker.sh build",
```

Thank you,
KK

**Comment by CCodie** [comment] 2019-01-03 00:21
@kk2491 , Thanks for detail reply. Are you now using VScode for debugging?
@davidhopper2003 , I wonder that I don't need to build ApolloProject again in VScode if I already built it in terminal previously. Thanks.

**Comment by davidhopper2003** [comment] 2019-01-04 02:04
@CCodie If you have compiled the Apollo project in a terminal, you don't have to compile it with VSCode again.

**Comment by natashadsouza** [comment] 2019-03-12 23:22
Closing this issue as it appears to be resolved. Feel free to reopen should the issue persist. Thanks!

**Closed by natashadsouza** 2019-03-12 23:22 UTC
Labels: Apollo 3.0, Module: Build, Type: Question

**Comment by Avps1** [comment] 2020-05-25 09:56
> @kk2491 , Thanks for detail reply. Are you now using VScode for debugging? I want to debug perception module with VScode and I would appreciate it if I could ask you about it.
> @davidhopper2003 , I wonder that I don't need to build ApolloProject again in VScode if I already built it in terminal previously. Thanks.

Hi @CCodie, 
Did you have any luck debugging the Perception module using VSCode ? I have followed this document https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_debug_using_vscode.md , but the problem is, the program does not stop at any of the set breakpoints while debugging. I also made a video of this problem - https://youtu.be/d9vcRATc3M0

Did you face similar problems ? 
Thanks in advance.

**Comment by Avps1** [comment] 2020-05-25 10:26
> > @kk2491 , Thanks for detail reply. Are you now using VScode for debugging? I want to debug perception module with VScode and I would appreciate it if I could ask you about it.
> > @davidhopper2003 , I wonder that I don't need to build ApolloProject again in VScode if I already built it in terminal previously. Thanks.
> 
> Hi @CCodie,
> Did you have any luck debugging the Perception module using VSCode ? I have followed this document https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_debug_using_vscode.md , but the problem is, the program does not stop at any of the set breakpoints while debugging - https://github.com/ApolloAuto/apollo/issues/11107-I also made a video of this problem - https://youtu.be/d9vcRATc3M0
> 
> Did you face similar problems ?
> Thanks in advance.
