### ISSUE TITLE
[v9.0.0-beta],error "Build failed! "

### ISSUE THREAD

**Issue by tedelon** [ApolloAuto/apollo#15191] opened 2023-11-10 05:51 UTC
### System information
- **NVIDIA orin Ubuntu 20.04**:
- **Apollo installed from source **:
- **Apollo version (v9.0.0-beta)**:

### Steps to reproduce the issue:
- ****:ENTER the container : sudo bash ./apollo.sh build 

### Supporting materials (screenshots, command lines, code/script snippets):
![Screenshot from 2023-11-10 13-46-39](https://github.com/ApolloAuto/apollo/assets/49553101/ef757954-654f-4160-a0dc-d51f4fb92295)

if the command "sudo bash ./apollo.sh build_opt",diaplay the error "Compiling adler32.c failed"
![image](https://github.com/ApolloAuto/apollo/assets/49553101/6d58b4e6-3194-4db4-8b2c-591c7fc28db0)

then a different error is displayed for each validation
![image](https://github.com/ApolloAuto/apollo/assets/49553101/c1ed3632-4047-489a-b31c-d8defe5e7f33)

**Comment by tedelon** [comment] 2023-11-13 05:11
build failed 
 maybe wrong with the file . maybe use vpn???
https://storage.googleapis.com/grpc-bazel-mirror/github.com/madler/zlib/archive/cacf7f1d4e3d44d871b605da3b647f07d718623f.tar.gz
![Screenshot from 2023-11-12 21-04-47](https://github.com/ApolloAuto/apollo/assets/49553101/2234c7a5-f2fa-4442-93a2-fad7b849e6d7)

**Comment by tangjiacai101** [comment] 2023-11-14 05:15
I also encountered the same problem

**Comment by tedelon** [comment] 2023-11-14 05:54
**[run 2rd error]** :maybe the setuptools version  issues case
use lower version,but still build failed,also other error

**aarch64-linux-gnu-gcc-9: error: unrecognized command line option ‘-mavx2’**

![image](https://github.com/ApolloAuto/apollo/assets/49553101/003a6ecd-281f-40cc-9586-c9b0a209fdff)

**Comment by WildBeast114514** [comment] 2023-11-14 07:43
> **[run 2rd error]** :maybe the setuptools version issues case use lower version,but still build failed,also other error
> 
> **aarch64-linux-gnu-gcc-9: error: unrecognized command line option ‘-mavx2’**
> 
> ![image](https://user-images.githubusercontent.com/49553101/282676150-003a6ecd-281f-40cc-9586-c9b0a209fdff.png)

avx2 is an instruction set for the x86 architecture and is not available in the arm architecture.
The default build instruction set for the arm architecture should be `-march=native`, check if you have a `.buildtool.conf` file under your `/apollo` directory, and if the file contains something like this:
```
[compile]
march=-mavx2
```
If so, delete the file and compile again

**Comment by tedelon** [comment] 2023-11-14 08:48
> > **[run 2rd error]** :maybe the setuptools version issues case use lower version,but still build failed,also other error
> > **aarch64-linux-gnu-gcc-9: error: unrecognized command line option ‘-mavx2’**
> > ![image](https://user-images.githubusercontent.com/49553101/282676150-003a6ecd-281f-40cc-9586-c9b0a209fdff.png)
> 
> avx2 is an instruction set for the x86 architecture and is not available in the arm architecture. The default build instruction set for the arm architecture should be `-march=native`, check if you have a `.buildtool.conf` file under your `/apollo` directory, and if the file contains something like this:
> 
> ```
> [compile]
> march=-mavx2
> ```
> 
> If so, delete the file and compile again


sorry ,I can't find the file."buildtool.conf"
can you show the path in detail?

**Comment by WildBeast114514** [comment] 2023-11-14 09:18
> > > **[run 2rd error]** :maybe the setuptools version issues case use lower version,but still build failed,also other error
> > > **aarch64-linux-gnu-gcc-9: error: unrecognized command line option ‘-mavx2’**
> > > ![image](https://user-images.githubusercontent.com/49553101/282676150-003a6ecd-281f-40cc-9586-c9b0a209fdff.png)
> > 
> > 
> > avx2 is an instruction set for the x86 architecture and is not available in the arm architecture. The default build instruction set for the arm architecture should be `-march=native`, check if you have a `.buildtool.conf` file under your `/apollo` directory, and if the file contains something like this:
> > ```
> > [compile]
> > march=-mavx2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If so, delete the file and compile again
> 
> sorry ,I can't find the file."buildtool.conf" can you show the path in detail?

This file should be in here `/apollo/.buildtool.conf`.
Just delete it, we will fix this bug in next commit.

**Comment by kuang2022** [comment] 2023-11-15 09:46
During compilation, I ran into a build failure error.
``(01:38:40) INFO: Found 1 target...
(01:39:00) ERROR: /apollo/modules/drivers/video/tools/decode_video/BUILD:6:17: Linking modules/drivers/video/tools/decode_video/video2jpg failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc @bazel-out/aarch64-opt/bin/modules/drivers/video/tools/decode_video/video2jpg-2.params

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
/usr/bin/ld:bazel-out/aarch64-opt/bin/_solib_local/_U@can_Ucard_Ulibrary_S_S_Chermes_Ucan___Ulib/libbcan.so: file format not recognized; treating as linker script
/usr/bin/ld:bazel-out/aarch64-opt/bin/_solib_local/_U@can_Ucard_Ulibrary_S_S_Chermes_Ucan___Ulib/libbcan.so:0: syntax error
collect2: error: ld returned 1 exit status
Target //modules/drivers/video:install failed to build
Use --verbose_failures to see the command lines of failed build steps.
(01:39:01) INFO: Elapsed time: 22.712s, Critical Path: 18.45s
(01:39:01) INFO: 205 processes: 192 internal, 13 linux-sandbox.
(01:39:01) FAILED: Build did NOT complete successfully
(01:39:01) FAILED: Build did NOT complete successfully
[buildtool] 2023-11-15 09:39:01 ERROR Encounter ErrCode.BazelErr
[buildtool] 2023-11-15 09:39:01 ERROR hint: Install package drivers-video source failed!
[buildtool] 2023-11-15 09:39:01 ERROR solution: Please checkout the build file by following bazel error hints`
<img width="810" alt="微信图片_20231115094527" src="https://github.com/ApolloAuto/apollo/assets/108571450/b1452516-b842-4b85-99e7-e5def3c579d9">

**Comment by WildBeast114514** [comment] 2023-11-16 07:52
> During compilation, I ran into a build failure error. ``(01:38:40) INFO: Found 1 target... (01:39:00) ERROR: /apollo/modules/drivers/video/tools/decode_video/BUILD:6:17: Linking modules/drivers/video/tools/decode_video/video2jpg failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc @bazel-out/aarch64-opt/bin/modules/drivers/video/tools/decode_video/video2jpg-2.params
> 
> Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging /usr/bin/ld:bazel-out/aarch64-opt/bin/_solib_local/_U@can_Ucard_Ulibrary_S_S_Chermes_Ucan___Ulib/libbcan.so: file format not recognized; treating as linker script /usr/bin/ld:bazel-out/aarch64-opt/bin/_solib_local/_U@can_Ucard_Ulibrary_S_S_Chermes_Ucan___Ulib/libbcan.so:0: syntax error collect2: error: ld returned 1 exit status Target //modules/drivers/video:install failed to build Use --verbose_failures to see the command lines of failed build steps. (01:39:01) INFO: Elapsed time: 22.712s, Critical Path: 18.45s (01:39:01) INFO: 205 processes: 192 internal, 13 linux-sandbox. (01:39:01) FAILED: Build did NOT complete successfully (01:39:01) FAILED: Build did NOT complete successfully [buildtool] 2023-11-15 09:39:01 ERROR Encounter ErrCode.BazelErr [buildtool] 2023-11-15 09:39:01 ERROR hint: Install package drivers-video source failed! [buildtool] 2023-11-15 09:39:01 ERROR solution: Please checkout the build file by following bazel error hints` <img alt="微信图片_20231115094527" width="810" src="https://user-images.githubusercontent.com/108571450/283074260-b1452516-b842-4b85-99e7-e5def3c579d9.png">



> build failed maybe wrong with the file . maybe use vpn??? https://storage.googleapis.com/grpc-bazel-mirror/github.com/madler/zlib/archive/cacf7f1d4e3d44d871b605da3b647f07d718623f.tar.gz ![Screenshot from 2023-11-12 21-04-47](https://user-images.githubusercontent.com/49553101/282369047-2234c7a5-f2fa-4442-93a2-fad7b849e6d7.png)
> 
> run 2rd ![image](https://user-images.githubusercontent.com/49553101/282374184-9780cd21-2972-4034-8073-d361eecf75e1.png)

in this 2rd build error, we found it's caused by the version mismatched between local build package and remote package.
We have fixed this bug, please upgrade the buildtool in your container:
```
sudo apt update && sudo apt install --only-upgrade apollo-neo-buildtool && rm -rf /apollo/.buildtool.conf
```

**Comment by WildBeast114514** [comment] 2023-11-16 08:07
> During compilation, I ran into a build failure error. ``(01:38:40) INFO: Found 1 target... (01:39:00) ERROR: /apollo/modules/drivers/video/tools/decode_video/BUILD:6:17: Linking modules/drivers/video/tools/decode_video/video2jpg failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc @bazel-out/aarch64-opt/bin/modules/drivers/video/tools/decode_video/video2jpg-2.params
> 
> Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging /usr/bin/ld:bazel-out/aarch64-opt/bin/_solib_local/_U@can_Ucard_Ulibrary_S_S_Chermes_Ucan___Ulib/libbcan.so: file format not recognized; treating as linker script /usr/bin/ld:bazel-out/aarch64-opt/bin/_solib_local/_U@can_Ucard_Ulibrary_S_S_Chermes_Ucan___Ulib/libbcan.so:0: syntax error collect2: error: ld returned 1 exit status Target //modules/drivers/video:install failed to build Use --verbose_failures to see the command lines of failed build steps. (01:39:01) INFO: Elapsed time: 22.712s, Critical Path: 18.45s (01:39:01) INFO: 205 processes: 192 internal, 13 linux-sandbox. (01:39:01) FAILED: Build did NOT complete successfully (01:39:01) FAILED: Build did NOT complete successfully [buildtool] 2023-11-15 09:39:01 ERROR Encounter ErrCode.BazelErr [buildtool] 2023-11-15 09:39:01 ERROR hint: Install package drivers-video source failed! [buildtool] 2023-11-15 09:39:01 ERROR solution: Please checkout the build file by following bazel error hints` <img alt="微信图片_20231115094527" width="810" src="https://user-images.githubusercontent.com/108571450/283074260-b1452516-b842-4b85-99e7-e5def3c579d9.png">

In our local test, we can't reproduce the problem.
Everything when well during building drivers-video package:
<img width="720" alt="f687b113b8aec789ec9f186b9" src="https://github.com/ApolloAuto/apollo/assets/49615494/d70f6404-29e3-4b23-84c4-d2387c1f925e">
Can your provide the output of following command so we can further troubleshoot this issue:
```
ll /opt/apollo/neo/packages/3rd-can-card-library/local/lib/

for f in `ls /opt/apollo/neo/packages/3rd-can-card-library/local/lib/`; do file /opt/apollo/neo/packages/3rd-can-card-library/local/lib/$f; done
```

**Comment by kuang2022** [comment] 2023-11-16 08:49
When we initially built the container, we pulled dev_start.sh script or orin.dev.aarch64.sh script. I'm pulling dev_start.sh

**Comment by WildBeast114514** [comment] 2023-11-17 02:22
The issue of @tedelon have been fixed in  https://github.com/ApolloAuto/apollo/commit/e05afd63bbadb0a57c2cd3e4326c89850b2192a8
We will close this issue. If you encounter any new issue during using apollo, please open a new one

**Closed by WildBeast114514** 2023-11-17 02:22 UTC
Labels: Type: Bug, Module: Build
