### ISSUE TITLE
Localhost:8888  page not found

### ISSUE THREAD

**Issue by yangyangyiming** [ApolloAuto/apollo#3972] opened 2018-04-20 02:21 UTC
![workspace 1_002](https://user-images.githubusercontent.com/36982804/39027200-6b82d3aa-4483-11e8-85fe-7e65c6bd02ea.png)
Something unexpected happened, Dreamview appeared only once... After the only success, I tried many times, localhost:8888 appeared just like this: 'page not found. '
Why is this and how can I solve the problem?
Thank you.

**Comment by jmtao** [comment] 2018-04-20 18:02
@yangyangyiming pull the latest code, and try again?
- exit docker 
- pull the latest code
- restart docker
- into docker
- apollo.sh build

**Comment by yangyangyiming** [comment] 2018-04-21 02:10
I will try. Thank you so much!

**Comment by yangyangyiming** [comment] 2018-04-21 02:11
@jmtao 
I will try. Thank you so much!

**Comment by yangyangyiming** [comment] 2018-04-21 04:32
@jmtao  Not working...
![workspace 1_003](https://user-images.githubusercontent.com/36982804/39080384-ab9b247e-455f-11e8-9ec7-c5b8a99103b7.png)
I followed your advice and pulled the latest code, it still cannot access Dreamview.

**Comment by yangyangyiming** [comment] 2018-04-22 07:36
Some details:
someone help!
![selection_005](https://user-images.githubusercontent.com/36982804/39092551-d4f58d62-4642-11e8-9408-b4a2e77c2290.png)

**Comment by zhxt** [comment] 2018-04-22 08:33
@yangyangyiming Could you please check if the dreamview process is running. 
```
ps aux | grep dreamview
#or 
pgrep dreamvew
```

**Comment by yangyangyiming** [comment] 2018-04-22 08:45
@zhxt 
![ubuntu in_dev_docker -apollo_006](https://user-images.githubusercontent.com/36982804/39093103-7b6c3e4e-464c-11e8-950c-15f72a7d7796.png)

**Comment by zhxt** [comment] 2018-04-22 12:59
@yangyangyiming hmmm, seems like you write the second cmd  right, but it's nothing got from pgrep, so seems dreamview is not running correctly.

Could you please double check the dreamview process to make sure it's really running?
After you execute bootstrap.sh, wait about one minute then check ps/pgrep, because supervisord will restart the process several times if it failed.

**Comment by yangyangyiming** [comment] 2018-04-22 13:59
@zhxt 
The results are as follows:
![ubuntu in_dev_docker -apollo_007](https://user-images.githubusercontent.com/36982804/39095751-3fde564c-4678-11e8-8876-aa4e2ede7be1.png)

**Comment by yangyangyiming** [comment] 2018-04-22 14:09
@zhxt 
The ufw's status is inactive and my network is not using any proxy.

**Comment by yangyangyiming** [comment] 2018-04-22 14:25
@zhxt 
Yes

**Comment by zhxt** [comment] 2018-04-22 14:29
@yangyangyiming  Then try to start it manually to see what will happen,
```
#inside docker
source  scripts/apollo_base.sh

supervisorctl start dreamview 
or
supervisorctl -c /apollo/modules/tools/supervisord/dev.conf start dreamview 
or
/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/dreamview/conf/dreamview.conf
```
```

**Comment by yangyangyiming** [comment] 2018-04-23 02:05
@zhxt  There seems to be some problems:
![ubuntu in_dev_docker -apollo_008](https://user-images.githubusercontent.com/36982804/39103069-3807c40e-46db-11e8-8eba-2ff26115e010.png)
![selection_009](https://user-images.githubusercontent.com/36982804/39103514-bdfa9a9e-46dd-11e8-9907-43e7882bad3b.png)

**Comment by zhxt** [comment] 2018-04-24 05:04
The first command's output prompts dreamview  is already running.

**Comment by yangyangyiming** [comment] 2018-04-24 13:05
@zhxt 
Could it be the problem with these warnings?
![ubuntu in_dev_docker -apollo_010](https://user-images.githubusercontent.com/36982804/39188628-ccad23d8-4802-11e8-9afc-b030935c0384.png)

**Comment by zhxt** [comment] 2018-04-24 17:13
@yangyangyiming 

Maybe I didn't make it clearly, so I repeat again for you:

The web server is living in dreamview, you can't get dreamview working, then you can't access it.

1. Try to find out if dreamview is currently running correctly;
2. If not, find out why.

I have already told you how to achieve this in the conversation above, but I feel  you're just trying to ignore that, without the answers, we won't know where the problem is.

Leaning how to solve a problem is much important than solve the problem itself.

If you still have troubles with this, ping me at #apolloauto channel on freenode IRC.
Good luck!

**Comment by yangyangyiming** [comment] 2018-04-25 02:47
@zhxt    Very very thank you for your guide and patiance ! I saw my problems and I will adjust the way at solving problems. Thank you !

**Comment by zhxt** [comment] 2018-04-25 15:28
@yangyangyiming Hey, I didn't mean to be rude, I just think IRC is much **efficient** than github issues, since it's a **instant communication** tool. If you feel more convenience with github issues, we can still talking here.

* I have the build warnings too, that doesn't affect on dreamview. 
* After execute `bash scripts/bootstrap.sh`, Supervisord will restart dreaview 10 times if it failed :
https://github.com/ApolloAuto/apollo/blob/4960c97019b7d475709e178c5c69551403513ea4/modules/tools/supervisord/dev.conf#L108-L116
So  wait for a moment, then check if we can got it in ps/pgrep after that. 
* The presupposition of manually start dreamview is it's not currently running.
* if it's not running, gdb will find where it crashed and the backtrace.
* if it's running, then check the logs under data/log/dreamview.[INFO, WARNING,ERROR].

**Comment by yangyangyiming** [comment] 2018-04-26 04:04
@zhxt  Hahaha! It worked ! I do have difficulties and problems in reading codes and doing some complex examines...but I will make more efforts. So I reinstalled the system : replaced ubuntu14.04 with ubuntu16.04 and then it's OK(though I don't know why...)
Now I want to know how to quit Dreamview and docker correctly after simulation :smile: 
![apollo-succeed](https://user-images.githubusercontent.com/36982804/39284919-40561948-4948-11e8-94e8-5b52d7050f1f.png)

**Comment by jmtao** [comment] 2018-04-26 18:33
@yangyangyiming great you've made it work.  And many thanks to @zhxt for helping it out. 
We will close the issue for now. 

Thank you for supporting Apollo!

**Closed by jmtao** 2018-04-26 18:33 UTC
Labels: Module: Docker, Type: Question

**Comment by Sirus1110** [comment] 2023-08-14 08:48
After I execute the following command:
`supervisorctl -c /apollo/modules/tools/supervisord/dev.conf start dreamview`
Terminal display: dreamview: started
But dreamview keeps happening coredump
_________________________________________
我执行下面的命令之后：
supervisorctl -c /apollo/modules/tools/supervisord/dev.conf start dreamview 
终端显示：dreamview: started
但是dreamview一直在发生coredump
