### ISSUE TITLE
The real-time relative map can't be displayed correctly in Dreamview for Apollo master branch (May 8, 2019)

### ISSUE THREAD

**Issue by davidhopper2003** [ApolloAuto/apollo#8247] opened 2019-05-09 12:18 UTC
**Describe the bug**
A bag file (`csc_hw_right.bag`) was recorded using the `rosbag` command. The bag file was converted to a record file (`csc_hw_right.record`) using the `rosbag_to_record csc_hw_right.bag csc_hw_right.record` command . The real-time relative map was generated using this `record` file. However,  the map is displayed in chaos in Dreamview and the web page shows nothing when the F5 key is pressed to refresh the display. The source code was downloaded from the latest master branch (May 8, 2019, commit id `2f308aac31e13a4c234e3b12010116333af398e6`) based on the Cyber RT framework. The `/apollo/relative_map` topic is displayed properly through the `cyber_monitor` tool.

**To Reproduce**
1. download the latest master branch source code. 
``` bash
git pull --rebase upstream master
git reset --hard git reset --hard 2f308aac31e13a4c234e3b12010116333af398e6
```
2. start and enter the docker. 
``` bash
bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh
```
3. build the apollo project. 
``` bash
bash apollo.sh build -j 8
```
4. convert the bag file to a record file. 
``` bash
rosbag_to_record data/bag/csc_hw_right.bag data/bag/csc_hw_right.record
```
5. modify the `modules/common/data/global_flagfile.txt` file as follows: 
  change
``` 
--use_navigation_mode=false
```
to  
``` 
--use_navigation_mode=true
```
and add a line:
``` 
--local_utm_zone_id=49
```
![global_flagfile_config](https://user-images.githubusercontent.com/31435476/57450746-db810180-7291-11e9-9cab-bd571525a258.png)

6. modify the `modules/localization/conf/localization.conf` file as follows: 
  change
``` 
--local_utm_zone_id=10
```
to  
``` 
--local_utm_zone_id=49
```
![localization_config](https://user-images.githubusercontent.com/31435476/57453717-a9739d80-7299-11e9-934c-2b6d3263710a.png)

7. start Dreaview:
``` bash
bash scripts/bootstrap.sh
```

8. On the Dreamview web page, enable the `Relative Map` module and confirm that it is currently in `Navigation` Mode.
![dreamview_in_relative_map_and_navigation_mode](https://user-images.githubusercontent.com/31435476/57453740-bb554080-7299-11e9-87c7-6bfe7e52e24d.png)

9. Replay the record file:
``` bash
cyber_recorder play -f data/bag/csc_hw_right.record -l
```
10. Send a navigation line:
``` bash
bash scripts/navigator.sh data/bag/csc_hw_right.smoothed
```

**Expected behavior**
The real-time relative map with one lane is correctly displayed in Dreamview and the web page can be updated correctly when the F5 key is pressed to refresh the display.

**Actual results**
The real-time relative map with one lane is displayed in chaos in Dreamview and the web page shows nothing when the F5 key is pressed to refresh the display.

**Screenshots**
![dreamview_in_chaos](https://user-images.githubusercontent.com/31435476/57453766-ca3bf300-7299-11e9-90d7-1ebf3d72d291.png)
The real-time relative map with one lane is displayed in chaos

![dreamview_in_chaos_after_refresh](https://user-images.githubusercontent.com/31435476/57453775-cf993d80-7299-11e9-8bc9-d7558f393653.png)
The web page shows nothing when the F5 key is pressed to refresh the display.

![relative_map_topic](https://user-images.githubusercontent.com/31435476/57453794-e17ae080-7299-11e9-84a2-dd6c860f5321.png)
![relatvie_map_topic_in_detail](https://user-images.githubusercontent.com/31435476/57453795-e2ac0d80-7299-11e9-85a3-12d36619422a.png)
The `/apollo/relative_map` topic is displayed properly through the `cyber_monitor` tool.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: Chrome 68.0.3440.106 (Official Build) (64-bit)
 - Apollo Version: master branch (May 8, 2019, commit id `2f308aac31e13a4c234e3b12010116333af398e6`)

**Data file**
URL: https://pan.baidu.com/s/1qyXyR94Yhhug28ahzkZtuw 
Key: t95z

**Comment by davidhopper2003** [comment] 2019-05-10 00:48
@natashadsouza  Thank you. 
It's a problem not for Apollo 2.5 but for Apollo version 3.5 and above.  In fact, the real-time relative map is displayed correctly with Dreamview for Apollo 3.0 and below. However, there are some displaying problems with Dreamview for Apollo version 3.5 and above.

**Comment by natashadsouza** [comment] 2019-05-10 01:27
@davidhopper2003 noted. Thank you very much. Waiting on @vlin17 for a response.

**Comment by davidhopper2003** [comment] 2019-05-10 03:19
@natashadsouza Sure. Thanks once more.

**Comment by vlin17** [comment] 2019-05-11 00:43
Thank you for always providing reproduction steps in details, that definitely speed up the debugging process. The code was assuming map_geometry's CurveSegment always has start_position defined, we have updated our code to consider the situation where no start_position is given. Please try again after https://github.com/ApolloAuto/apollo/pull/8276 is delivered.

**Comment by davidhopper2003** [comment] 2019-05-11 01:18
@vlin17 Thank you very much. You are awesome. The contribution of the Apollo team is gorgeous and it is a great honour to submit a bug for your team.

**Comment by natashadsouza** [comment] 2019-05-13 21:25
Thank you @davidhopper2003 for your encouraging words. We truly appreciate your support in reporting new bugs to us!
Closing this issue currently.

**Closed by natashadsouza** 2019-05-13 21:25 UTC
Labels: Module: Simulation & Dreamview, Type: Bug, Type: Help wanted

**Comment by jp12AI** [comment] 2021-09-11 17:23
@davidhopper2003 I'm trying to use navigation mode or relative map for apollo 5.0 however, I get an error while using navigator.sh script because it looks for a directory that doesn't exist. Could you please tell me the steps between 9 and 10 that you didn't list? Did you use record_extractor to convert to text then smooth? Any help on this would be appreciated. Thank you.
