### ISSUE TITLE
how to filter .record some channel name's message? 

### ISSUE THREAD

**Issue by LawranceXcl** [ApolloAuto/apollo#11160] opened 2020-04-29 08:42 UTC
how to filter .record some channel name's message? just like the command "ros filter"

**Comment by jmtao** [comment] 2020-04-29 23:00
@LawranceXcl  you can use "cyber_recorder split"
in docker, "cyber_recorder split --help".
e.g. "cyber_recorder split -f 1.record  -kill /apollo/planning" can filter out topic /apollo/planning.

**Comment by LawranceXcl** [comment] 2020-04-30 10:37
Thks!  
After run the command "cyber_recorder split -f demo_3.5.record -kill /apollo/planning",I found that demo_3.5.record.split was generated. Then, I run the command "cyber_recorder play -f docs/demo_guide/demo_3.5.record.split -l"and on the other terminator ,I run the command "cyber_channel list ".   "/apollo/planning" channel name still exists.How about this?

**Comment by LawranceXcl** [comment] 2020-04-30 10:38
@jmtao

**Comment by jmtao** [comment] 2020-05-07 22:29
@LawranceXcl are you sure? I'm unable to reproduce it on my side. can you try it again? please make sure there's no planning instance running on your server at all.

**Comment by jmtao** [comment] 2020-05-26 22:53
@LawranceXcl hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!

**Closed** 2020-05-26 22:53 UTC
