### ISSUE TITLE
Perception module involves tracking ? 

### ISSUE THREAD

**Issue by rlaehddls9** [ApolloAuto/apollo#13889] opened 2021-06-25 11:32 UTC
env : ubuntu 18.04, apollo v6.0 

Hello I run the lidar perception module by using this page.(https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md)
Below is the result video. (I got raw data with hesai64)

https://user-images.githubusercontent.com/79086973/123418744-60574280-d5f4-11eb-87c9-8d15408fc305.mov

In step 8, I run 
cyber_launch start /apollo/modules/perception/production/launch/perception_lidar.launch 
In this case, perception_lidar.launch file has a tracking module? 
If not, how can I run the perception module with tracking ? (I want to run lidar perception with tracking)

**Comment by daohu527** [comment] 2021-06-26 06:58
The lidar module is default with tracking.

You can confirm it by checking the ID on the obstacle. If the ID does not change, it means it is work. If the ID of the same obstacle changes frequently, it means it is not work. 

Your video resolution is too small to see clearly!

**Comment by rlaehddls9** [comment] 2021-06-28 02:32
Thanks for the reply.

How to check the obstacle id?

**Comment by rlaehddls9** [comment] 2021-06-28 02:47
Thanks for the reply.

This video is part of the full video. There are quite a few cases where the bounding box is recognized and then disappears and then reappears, but the ID value is changing every time it happens. It seems that tracking is not being applied in this case, how to solve it?

**Comment by rlaehddls9** [comment] 2021-06-28 04:34
This is the cyber_monitor for the perception module video above. 

<img width="573" alt="cyber_monitor" src="https://user-images.githubusercontent.com/79086973/123580766-7001a180-d815-11eb-84a5-6a12c035c3cc.png">

**Comment by daohu527** [comment] 2021-06-28 07:22
Why the `/apollo/sensor/hesai64/PointCloud2` frequency is doubled. 

I think the tracking is already in effect, because you can see that the id of the obstacle that has not disappeared is constant. 

So the remaining question is why the obstacle disappears?

**Comment by rlaehddls9** [comment] 2021-06-28 07:42
https://user-images.githubusercontent.com/79086973/123597602-80724600-d82e-11eb-997e-5c98d24e49d0.mp4

This video is raw data of using hesai lidar. 
When I saw raw data, I can't find any problem in this case. 
In generally, how obstacle disappearing problems are happened?

+
Why the /apollo/sensor/hesai64/PointCloud2 frequency is doubled.
I can't understand this comment. Is that any prob?

**Comment by daohu527** [comment] 2021-06-28 09:48
`/apollo/sensor/hesai64/PointCloud2` frequency is normally 10HZ, but the frequency in your screenshots is 20HZ. The strange thing is that if the frequency of `/apollo/sensor/hesai64/PointCloud2` is 20HZ, then the frequency of `/apollo/perception/obstacles` should also be 20HZ

You should check the frequency and find out if there is an error message `data\log`

**Comment by rlaehddls9** [comment] 2021-06-28 11:45
How can I check and change the frequency ? 

(You should check the frequency and find out if there is an error message data\log)

Also How can I check an error message data\log ... ? 
As far as I can see, there was no error message when running the perception module.

I'm not familiar with Apollo yet, so please understand that the question is inexperienced...

**Comment by daohu527** [comment] 2021-06-28 13:56
From the above information, I can’t tell what the problem is, you need to try to analyze it

**Comment by rlaehddls9** [comment] 2021-06-28 15:42
Thanks for your reply !

**Comment by rlaehddls9** [comment] 2021-06-30 05:22
@daohu527 
Through lidar settings, /apollo/sensor/hesai64/PointCloud2 frquency was changed to 10HZ. 

<img width="607" alt="cyber_monitor2" src="https://user-images.githubusercontent.com/79086973/123906084-80994f80-d9ae-11eb-9171-97d020691ccd.png">

But the frequency of /apollo/perception/obstacles is about 8Hz, is this difference causing the problem of objects disappearing?

The problem that the bounding box of an object is drawn well, disappears right next to the vehicle and then reappears. Do you know the common cause?

**Comment by rlaehddls9** [comment] 2021-06-30 11:23
https://drive.google.com/file/d/1TObm97yCTQ60ODfKXIRuTcfvVa-bpg5P/view?usp=sharing 

https://drive.google.com/file/d/1TObm97yCTQ60ODfKXIRuTcfvVa-bpg5P/view?usp=sharing 

This is a video of running the perception module on the raw data received by hesai pandar64.

You can see the problem that the bounding box of an object is drawn well first, but disappears right next to the vehicle and then reappears. 

If you have a solution, please let me know, I would appreciate it.

**Comment by daohu527** [comment] 2021-06-30 14:18
I don't know what the problem is, why is the system localization frequency 200? Are you sure you only activate Apollo, or additional changes.

I guess there are duplicate news releases, and the current frame is overwritten

```
/apollo/canbus/chassis
/apollo/localization/pose
```

**Comment by rlaehddls9** [comment] 2021-07-01 03:47
Ok, Thanks for your reply. 

I try to analyze the prob!

**Comment by zhangchuang-zc** [comment] 2021-07-14 09:30
hello!@rlaehddls9 
I run cyber_launch start /apollo/modules/perception/production/launch/perception_lidar.launch, but the process is stuck for several hours. As shown in the figure, i have to close this process. Do you have this problem? How long did your process (Perception_lidar.launch) take？
Thanks！
<img width="726" alt="微信截图_20210714172826" src="https://user-images.githubusercontent.com/70929690/125598877-3f4933ca-6b4b-41b5-a2ea-12876ce74858.png">

**Comment by daohu527** [comment] 2021-07-14 10:40
From the picture, there is a problem with your map.

The lane `2563a_1_-1` is to narrow to pass a car. At the same time, I suggest you open a new issue. If there are different problems, it is convenient for others to solve the problem.

**Comment by rlaehddls9** [comment] 2021-07-15 06:54
Hello @zhangchuang-zc
I had same prob such as your image. But I changed perception_common.flag's obs_enable_hdmap_input=false then error message was disappeared. Also I can run the perception_lidar.launch without hdmap. In Dreamview, I can see the running module at Navigation mode.

**Comment by daohu527** [comment] 2022-08-27 13:21
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.

**Closed by daohu527** 2022-08-27 13:21 UTC
Labels: Module: Perception
