### ISSUE TITLE
./apollo.sh build_no_perception dbg   build failed

### ISSUE THREAD

**Issue by adderllyer** [ApolloAuto/apollo#3558] opened 2018-03-23 03:37 UTC
platform: ubuntu 16.04 without GPU

steps:
bash docker/scripts/install_docker.sh
docker ps  
bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh
./apollo.sh build_no_perception dbg

**build failed with error:**

```
ros@in_dev_docker:/apollo$ ./apollo.sh build_no_perception dbg
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
[INFO] Skip building perception module!
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
ERROR: error loading package 'query/540135163923dd7d5820f3ee4b306b32/install/_embedded_binaries/embedded_tools/third_party/checker_framework_javacutil': Extension file not found. Unable to load package for '//tools/build_rules:java_rules_skylark.bzl': BUILD file not found on package path
============================
[ERROR] Build failed!
[INFO] Took 1 seconds
============================
```

**Comment by xiaoxq** [comment] 2018-03-25 04:14
I cannot reproduce it.

Could you run
```
bazel clean
bazel query //...
```
and paste all the output here?

**Comment by adderllyer** [comment] 2018-03-27 08:21
following is the output 

star@in_dev_docker:/apollo$ bazel clean
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
............
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
star@in_dev_docker:/apollo$ bazel query //...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
ERROR: error loading package 'install/_embedded_binaries/embedded_tools/third_party/checker_framework_javacutil': Extension file not found. Unable to load package for '//tools/build_rules:java_rules_skylark.bzl': BUILD file not found on package path
Building: no action running

**Comment by xiaoxq** [comment] 2018-03-29 04:59
From the output, I can only tell that it's not about GPU or perception. It looks like a fundamental bazel environment problem, and unfortunately we cannot reproduce it.

I suggest you to start a new container from scratch and try it again.

**Comment by natashadsouza** [comment] 2018-08-27 23:42
Closing this issue as it seems to be resolved.

**Closed by natashadsouza** 2018-08-27 23:42 UTC
Labels: Module: Build, Module: Docker, Type: Question
