### ISSUE TITLE
the timestamp of tf while using tf2_ros static_transform_publisher

### ISSUE THREAD

**Issue by sinopec** [ApolloAuto/apollo#5447] opened 2018-08-22 05:50 UTC
while using tf2_ros static_transform_publisher ,the published tf msg will have a fixed timestamp
`rosrun tf2_ros static_transform_publisher 0 0 0 0 0 0 0 novatel velodyne16`

.And While I am using velodyne driver to transform point cloud data frome velodyne to world, I will Always have a error msg like this:

> Can not find transform frame: velodyne16. 1534916581.374434 Error info: Lookup would require extrapolation into the future.  Requested time 1534916581.374433994 but the latest data is at time 1534912854.099999905, when looking up transform from frame [velodyne16] to frame [world]. canTransform returned after 0.100629 timeout was 0.1. 

**DOse thie means i have to publish static_transform_publisher  repeatedly by using tf2_ros?
In tf we can add a period param in static_transform_publisher**

**Comment by jilinzhou** [comment] 2018-08-28 18:58
For us, the issue was fixed by feeding GPS time signal (from our gps module) into velodyne 16 directly.

**Comment by apollodevcommunity** [comment] 2021-02-07 07:23
I guess that the problem is caused by the mismatch between the time used by tf and the time used by ros msg. One possbile solution is to unify the time by the command: rosparam set /use_sim_time true. ——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=633

**Closed** 2021-03-05 10:59 UTC
Labels: Module: Driver, Type: Help wanted
