### ISSUE TITLE
bash apollo.sh build_cpu error with v2x package missing

### ISSUE THREAD

**Issue by springsun101** [ApolloAuto/apollo#6758] opened 2019-02-06 14:45 UTC
![image](https://user-images.githubusercontent.com/6998502/52348992-7d881800-2a1d-11e9-92f4-65a7537f1741.png)

The system is ubuntun 18.10 running in VM VirtualBox.

**Comment by natashadsouza** [comment] 2019-02-07 01:00
Refer to #6467 and let me know if you still face the issue.

**Comment by springsun101** [comment] 2019-02-07 08:26
> Refer to #6467 and let me know if you still face the issue.

![image](https://user-images.githubusercontent.com/6998502/52398756-081a5700-2ab2-11e9-96fc-ad489cadec68.png)

**Comment by aboarya** [comment] 2019-02-07 08:40
@springsun101 Are you behind a firewall or a proxy?

I think the error is `cannot open git-upload-pack`  and could be caused by a network issue.  Please see this [stackoverflow](https://stackoverflow.com/a/24533854/1158977) answer

**Comment by springsun101** [comment] 2019-02-07 12:20
> @springsun101 Are you behind a firewall or a proxy?
> 
> I think the error is `cannot open git-upload-pack` and could be caused by a network issue. Please see this [stackoverflow](https://stackoverflow.com/a/24533854/1158977) answer

Yes, I am behind a proxy.

**Comment by springsun101** [comment] 2019-02-08 08:40
> > @springsun101 Are you behind a firewall or a proxy?
> > I think the error is `cannot open git-upload-pack` and could be caused by a network issue. Please see this [stackoverflow](https://stackoverflow.com/a/24533854/1158977) answer
> 
> Yes, I am behind a proxy.

Build Problem solved.

**Comment by aboarya** [comment] 2019-02-08 12:07
What is the proxy issue or something else? If the proxy, how did you resolve it?

**Comment by springsun101** [comment] 2019-02-08 15:48
> What is the proxy issue or something else? If the proxy, how did you resolve it?

I switch to guest network and it can build now.

**Comment by natashadsouza** [comment] 2019-03-12 22:05
Currently closing this issue as it appears to be resolved. Feel free to reopen it if the issue persists. Thanks!

**Closed by natashadsouza** 2019-03-12 22:05 UTC
Labels: Module: Build, Type: Help wanted
