### ISSUE TITLE
ModuleNotFoundError: No module named 'cyber'

### ISSUE THREAD

**Issue by guo-pu** [ApolloAuto/apollo#13493] opened 2021-03-01 09:29 UTC
![image](https://user-images.githubusercontent.com/39380658/109477921-93a91b00-7ab3-11eb-88d9-95e3ce84855f.png)
How can we solve it?

**Comment by storypku** [comment] 2021-03-01 11:43
Duplicate of #13187 . Please run `./bazel-bin/modules/tools/sensor_calibration/odom_publisher` instead.

**Comment by guo-pu** [comment] 2021-03-01 12:15
thank ！！Ran successfully .

**Comment by guo-pu** [comment] 2021-03-01 12:16
Will it compile after I modify the code of odom_publisher.py?

**Comment by guo-pu** [comment] 2021-03-01 12:17
After I modified the code of odom_publisher.py; how to compile it?

**Comment by guo-pu** [comment] 2021-03-01 12:18
@storypku  Thank ！！Ran successfully .
After I modified the code of odom_publisher.py; how to compile it?

**Comment by storypku** [comment] 2021-03-01 12:21
Since `odom_publisher` is located under `modules/tools`, you can run `./apollo.sh build tools` to build all Bazel targets under `modules/tools`.

**Comment by guo-pu** [comment] 2021-03-01 12:30
Thank！！

**Comment by guo-pu** [comment] 2021-03-01 12:31
@storypku  Thank！！

**Comment by storypku** [comment] 2021-03-01 13:01
Hi @guo-pu , this issue is going to be closed now. If you have other questions, feel free to open another issue. Thank you.

**Closed by storypku** 2021-03-01 13:01 UTC
Labels: Module: Build
