### ISSUE TITLE
Error while running Offline Perception LowCost Visualizer (Apollo 2.5)

### ISSUE THREAD

**Issue by CCodie** [ApolloAuto/apollo#5589] opened 2018-08-31 05:27 UTC
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 14.04
- **Apollo installed from (source or binary)**: From source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: ver 3.0 (Cloned the master branch today)

### Steps to reproduce the issue:
- `./apollo.sh build_opt_gpu`
- I tried three config options and details for each case are described below.
### 1. First case
- in `/apollo/modules/perception/conf/perception_lowcost_vis.conf` file
I didn't change the pointing of dag streaming config (below is for default)
`--dag_config_path=modules/perception/conf/dag_camera_obstacle_offline_all.config`

- `bash scripts/bootstrap.sh`

- `bash scripts/perception_lowcost_vis.sh`

- `rosbag play data/bag/demo_2.5.bag -l --clock`

- At first, the pop-up window started normally.
![image](https://user-images.githubusercontent.com/37093857/44893047-3fc2ed00-ad23-11e8-809d-c9016693a02f.png)

- After running for a few seconds, it stopped with error like the below picture.
![image](https://user-images.githubusercontent.com/37093857/44893081-a21bed80-ad23-11e8-9c01-ba4979c6fed8.png)

- Warning file in directory `/apollo/data/log`

> Log file created at: 2018/08/31 13:54:14
> Running on machine: in_dev_docker
> Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
> W0831 13:54:14.724200 10240 yolo_camera_detector.cc:125] YoloCameraDetector options.intrinsic is nullptr. Use default
> W0831 13:54:16.740774 10240 fusion_subnode.cc:67] Failed to get LidarObjectData.
> W0831 13:54:16.740803 10240 fusion_subnode.cc:129] Failed to find lidar_event_id:pub_driven_event_id:1009;lane_event_id:1010;camera_event_id:1009;radar_event_id:1013;motion_event_id:1022
> W0831 13:54:16.740839 10240 visualization_subnode.cc:162] Failed to find camera_event_id_: vis_driven_event_id:1011;motion_event_id:1020;fusion_event_id:1011;
> W0831 13:54:16.740844 10240 visualization_subnode.cc:170] Failed to find radar_event_id_: vis_driven_event_id:1011;motion_event_id:1020;fusion_event_id:1011;
> W0831 13:54:16.740847 10240 visualization_subnode.cc:186] Failed to find cipv_event_id_: vis_driven_event_id:1011;motion_event_id:1020;fusion_event_id:1011;
> W0831 13:54:16.740851 10240 visualization_subnode.cc:202] Failed to find lane_event_id_: vis_driven_event_id:1011;motion_event_id:1020;fusion_event_id:1011;
> W0831 13:55:18.055183 10328 pbf_sensor_manager.cc:78] Cannot find sensor camera and create one in SensorManager
> W0831 13:55:18.071740 10328 pbf_sensor_manager.cc:78] Cannot find sensor radar and create one in SensorManager
> E0831 13:55:24.564011 10329 glfw_fusion_viewer.cc:1170] unknown lane object spatial label: 6
> E0831 13:55:24.567875 10329 glfw_fusion_viewer.cc:1170] unknown lane object spatial label: 7
> E0831 13:55:24.857381 10329 glfw_fusion_viewer.cc:1337] unknown lane spatial label: 6
> E0831 13:55:24.857585 10329 glfw_fusion_viewer.cc:1337] unknown lane spatial label: 7
> E0831 13:55:25.148046 10329 glfw_fusion_viewer.cc:1170] unknown lane object spatial label: 6
> E0831 13:55:25.162075 10329 glfw_fusion_viewer.cc:1170] unknown lane object spatial label: 7
> E0831 13:55:25.201470 10329 glfw_fusion_viewer.cc:1337] unknown lane spatial label: 6
> E0831 13:55:25.201602 10329 glfw_fusion_viewer.cc:1337] unknown lane spatial label: 7
> E0831 13:55:25.342521 10329 glfw_fusion_viewer.cc:1170] unknown lane object spatial label: 6
> E0831 13:55:25.347434 10329 glfw_fusion_viewer.cc:1170] unknown lane object spatial label: 7
> E0831 13:55:25.384829 10329 glfw_fusion_viewer.cc:1337] unknown lane spatial label: 6
> E0831 13:55:25.385010 10329 glfw_fusion_viewer.cc:1337] unknown lane spatial label: 7
> .....

### 2. Second case
- in `/apollo/modules/perception/conf/perception_lowcost_vis.conf` file
I changed the pointing of dag streaming config.
`--dag_config_path=modules/perception/conf/dag_camera_obstacle_offline_fusion_sync.config`

- `bash scripts/bootstrap.sh`

- `bash scripts/perception_lowcost_vis.sh`

- `rosbag play data/bag/demo_2.5.bag -l --clock`

- At first, the pop-up window started normally. (same as first case)

- After running for a few seconds, it stopped with error. (same as first case)

- Warning file in directory `/apollo/data/log`

> Log file created at: 2018/08/31 14:00:15
> Running on machine: in_dev_docker
> Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
> W0831 14:00:15.598984 10648 yolo_camera_detector.cc:125] YoloCameraDetector options.intrinsic is nullptr. Use default
> E0831 14:00:17.517926 10648 subnode_helper.cc:38] reserve is empty
> W0831 14:00:17.518034 10648 lane_post_processing_subnode.cc:61] Failed to find motion_event_id_:
> W0831 14:00:17.518039 10648 lane_post_processing_subnode.cc:62] Unable to project lane history information
> W0831 14:00:17.578570 10648 fusion_subnode.cc:67] Failed to get LidarObjectData.
> W0831 14:00:17.578593 10648 fusion_subnode.cc:94] motion service not inited
> W0831 14:00:17.578604 10648 fusion_subnode.cc:129] Failed to find lidar_event_id:pub_driven_event_id:1009;lane_event_id:1010;camera_event_id:1009;radar_event_id:1013;
> W0831 14:00:17.578624 10648 fusion_subnode.cc:167] Failed to find motion_event_id:pub_driven_event_id:1009;lane_event_id:1010;camera_event_id:1009;radar_event_id:1013;
> W0831 14:00:17.578645 10648 visualization_subnode.cc:162] Failed to find camera_event_id_: vis_driven_event_id:1011;fusion_event_id:1011;
> W0831 14:00:17.578650 10648 visualization_subnode.cc:170] Failed to find radar_event_id_: vis_driven_event_id:1011;fusion_event_id:1011;
> W0831 14:00:17.578653 10648 visualization_subnode.cc:186] Failed to find cipv_event_id_: vis_driven_event_id:1011;fusion_event_id:1011;
> W0831 14:00:17.578657 10648 visualization_subnode.cc:194] Failed to find motion_event_id_: vis_driven_event_id:1011;fusion_event_id:1011;
> W0831 14:00:17.578661 10648 visualization_subnode.cc:202] Failed to find lane_event_id_: vis_driven_event_id:1011;fusion_event_id:1011;
> W0831 14:00:19.227643 10737 pbf_sensor_manager.cc:78] Cannot find sensor camera and create one in SensorManager
> W0831 14:00:19.777694 10737 pbf_sensor_manager.cc:78] Cannot find sensor radar and create one in SensorManager
> E0831 14:00:25.523979 10738 glfw_fusion_viewer.cc:1170] unknown lane object spatial label: 6
> E0831 14:00:25.527379 10738 glfw_fusion_viewer.cc:1170] unknown lane object spatial label: 7
> E0831 14:00:25.821913 10738 glfw_fusion_viewer.cc:1337] unknown lane spatial label: 6
> E0831 14:00:25.822046 10738 glfw_fusion_viewer.cc:1337] unknown lane spatial label: 7
> E0831 14:00:26.067018 10738 glfw_fusion_viewer.cc:1170] unknown lane object spatial label: 6
> E0831 14:00:26.069794 10738 glfw_fusion_viewer.cc:1170] unknown lane object spatial label: 7
> E0831 14:00:26.098668 10738 glfw_fusion_viewer.cc:1337] unknown lane spatial label: 6
> E0831 14:00:26.098850 10738 glfw_fusion_viewer.cc:1337] unknown lane spatial label: 7
> E0831 14:00:26.217285 10738 glfw_fusion_viewer.cc:1170] unknown lane object spatial label: 6
> E0831 14:00:26.220636 10738 glfw_fusion_viewer.cc:1170] unknown lane object spatial label: 7
> E0831 14:00:26.246590 10738 glfw_fusion_viewer.cc:1337] unknown lane spatial label: 6
> E0831 14:00:26.246841 10738 glfw_fusion_viewer.cc:1337] unknown lane spatial label: 7
> .....

### 3. Third case
- in `/apollo/modules/perception/conf/perception_lowcost_vis.conf` file
I changed the pointing of dag streaming config.
`--dag_config_path=modules/perception/conf/dag_camera_obstacle_lane_motion_vis.config`

- `bash scripts/bootstrap.sh`

- `bash scripts/perception_lowcost_vis.sh`

- `rosbag play data/bag/demo_2.5.bag -l --clock`

- The pop-up window worked fine and I could see the entire demo2.5 file without stopping.

- But there is still warning log file like below.
> Log file created at: 2018/08/31 14:05:26
> Running on machine: in_dev_docker
> Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
> W0831 14:05:26.638870 10862 yolo_camera_detector.cc:125] YoloCameraDetector options.intrinsic is nullptr. Use default
> W0831 14:05:28.558130 10862 visualization_subnode.cc:170] Failed to find radar_event_id_: vis_driven_event_id:1012;camera_event_id:1008;motion_event_id:1020;lane_event_id:1012
> W0831 14:05:28.558140 10862 visualization_subnode.cc:178] Failed to find fusion_event_id_: vis_driven_event_id:1012;camera_event_id:1008;motion_event_id:1020;lane_event_id:1012
> W0831 14:05:28.558143 10862 visualization_subnode.cc:186] Failed to find cipv_event_id_: vis_driven_event_id:1012;camera_event_id:1008;motion_event_id:1020;lane_event_id:1012
> W0831 14:05:30.746726 10948 frame_content.cc:325] FrameContent::get_camera_objects() : No Objects found
> W0831 14:05:30.746752 10948 frame_content.cc:326] current_camera_timestamp_ : 0
> E0831 14:05:30.843833 10948 glfw_fusion_viewer.cc:1170] unknown lane object spatial label: 6
> E0831 14:05:30.849551 10948 glfw_fusion_viewer.cc:1170] unknown lane object spatial label: 7
> W0831 14:05:30.913410 10948 frame_content.cc:310] FrameContent::get_camera_image() : No image found
> W0831 14:05:30.913436 10948 frame_content.cc:311] current_image_timestamp_ : 0
> W0831 14:05:31.137588 10948 frame_content.cc:325] FrameContent::get_camera_objects() : No Objects found
> W0831 14:05:31.137624 10948 frame_content.cc:326] current_camera_timestamp_ : 0
> W0831 14:05:31.137634 10948 frame_content.cc:325] FrameContent::get_camera_objects() : No Objects found
> W0831 14:05:31.137639 10948 frame_content.cc:326] current_camera_timestamp_ : 0
> W0831 14:05:31.138350 10948 frame_content.cc:310] FrameContent::get_camera_image() : No image found
> W0831 14:05:31.138358 10948 frame_content.cc:311] current_image_timestamp_ : 0
> E0831 14:05:31.151773 10948 glfw_fusion_viewer.cc:1274] Get nullptr lane_map from camera frame supplement.
> W0831 14:05:31.184262 10948 frame_content.cc:325] FrameContent::get_camera_objects() : No Objects found
> W0831 14:05:31.184296 10948 frame_content.cc:326] current_camera_timestamp_ : 0
> E0831 14:05:31.417707 10948 glfw_fusion_viewer.cc:1170] unknown lane object spatial label: 6
> E0831 14:05:31.420408 10948 glfw_fusion_viewer.cc:1170] unknown lane object spatial label: 7
> E0831 14:05:31.447015 10948 glfw_fusion_viewer.cc:1337] unknown lane spatial label: 6
> E0831 14:05:31.447212 10948 glfw_fusion_viewer.cc:1337] unknown lane spatial label: 7
> E0831 14:05:31.557371 10948 glfw_fusion_viewer.cc:1170] unknown lane object spatial label: 6
> E0831 14:05:31.560035 10948 glfw_fusion_viewer.cc:1170] unknown lane object spatial label: 7
> E0831 14:05:31.582873 10948 glfw_fusion_viewer.cc:1337] unknown lane spatial label: 6
> E0831 14:05:31.582970 10948 glfw_fusion_viewer.cc:1337] unknown lane spatial label: 7
> E0831 14:05:31.683897 10948 glfw_fusion_viewer.cc:1170] unknown lane object spatial label: 6
> E0831 14:05:31.690500 10948 glfw_fusion_viewer.cc:1170] unknown lane object spatial label: 7
> E0831 14:05:31.721868 10948 glfw_fusion_viewer.cc:1337] unknown lane spatial label: 6
> E0831 14:05:31.722007 10948 glfw_fusion_viewer.cc:1337] unknown lane spatial label: 7
> .....

`dag_camera_obstacle_lane_motion_vis` did not stop while running against other cases.
So it seems certain subnode which is not in `dag_camera_obstacle_lane_motion_vis` has a critical probelm.

And error for glfw_fushin_viewer.cc is logged for all three cases.

Please help me to solve this problem. Thanks !

**Comment by xinwf** [comment] 2018-11-21 07:35
Chinese? I want to talk with you about the perception, In my machine, it can't pop up the window. There is no error in perception module, I don't know why, even I use rosbag command play official bag.

**Comment by CCodie** [comment] 2018-11-23 06:03
@xinwf Hi, I'm not Chinese but I can talk with you in English.
Actually I also met the same problem and I remember that the problem was a pop-up window not the perception module. And you can solve that problem with [How to Run Perception Module on Your Local Computer](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md) document. I installed the GPU driver on Ubuntu 14.04 with document instructions.

**Comment by xinwf** [comment] 2018-11-23 07:39
I have updated the perception module to the latest code, and then it still can't pop up the window, yes, it's not the problem of perception, I used a cpp code segment to test the glfw, it errors when compiling, the test code is in the following:
```
#include <iostream>
#include "GLFW/glfw3.h"

int main()
{
    if (!glfwInit())
    {
        std::cout << "glfwInit" << std::endl;
        glfwTerminate();
        return -1;
    }

    return 0;
}

```
the error is:
```
/tmp/ccaZLwjX.o: In function `main':
glfw.cpp:(.text+0x5): undefined reference to `glfwInit'
glfw.cpp:(.text+0x2f): undefined reference to `glfwTerminate'
collect2: error: ld returned 1 exit status
```
so, it is problem of glfw, ok, the visualization is not the necessary, but the perception module also has some problems, I play demo_2.5.bag without obstacles topic, everything works fine, but the obstacle topic can't output data, I don't know why, I have installed cuda and nvidia drivers correctly. When I run perception module, the GPU is indeed used by it. It is very strange.

**Comment by xinwf** [comment] 2018-11-23 10:52
@CCodie, I have searched this problem, maybe it is caused by nvidia driver, I should install the driver with relative params other than one step installtion. I will have a try.

**Comment by pengpingliang** [comment] 2018-11-28 05:19
@CCodie 

I face to the same problem as you wrote the 3 cases.    Did you resolve it？

and the error log is：
E1128 13:08:33.027091 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:33.127009 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:33.127079 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:33.327430 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:33.327455 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:33.327464 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:33.630843 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:33.630930 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:33.630975 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:33.926513 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:33.926545 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:33.926563 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:34.429540 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:34.429631 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:34.429661 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:34.724030 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:34.724102 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:34.724128 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:35.028817 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:35.028904 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:35.328100 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:35.328363 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:35.628762 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:35.931886 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:35.997916 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:08:36.277387 15092 pbf_track.cc:352] target timestamp is smaller than previous timestamp
E1128 13:09:50.439623 15097 event_manager.cc:71] EventQueue is FULL. id: 1012
E1128 13:09:50.439693 15097 event_manager.cc:73] clear EventQueue. id: 1012 size: 1000
E1128 13:10:11.902302 15095 event_manager.cc:71] EventQueue is FULL. id: 1008
E1128 13:10:11.902390 15095 event_manager.cc:73] clear EventQueue. id: 1008 size: 1000
E1128 13:10:11.906464 15091 event_manager.cc:71] EventQueue is FULL. id: 1014 
....

**Comment by jinjinhong** [comment] 2019-01-04 07:49
> @natashadsouza @weidezhang @techoe
> Does anybody know about this problem ...??

hello ,I have run apollo like yours,but it not pop-up window ,I don't known why,can you give me some advice?

**Comment by jinjinhong** [comment] 2019-01-04 07:50
@CCodie hello ,I have run apollo like yours,but it not pop-up window ,I don't known why,can you give me some advice?

**Comment by techoe** [comment] 2019-01-25 18:04
@CCodie, I think your machine is not powerful enough to handle the image data in real time. Please play the recorded bag in slower speed:
> rosbag play data/bag/demo_2.5.bag -l --clock -r 0.1

**Comment by techoe** [comment] 2019-03-21 00:14
I am closing it since there is no further question after last answer.

**Closed by techoe** 2019-03-21 00:14 UTC
Labels: Module: Perception, Type: Help wanted
