### ISSUE TITLE
Do we really need to launch the script docker/setup_host/setup_host.sh each time we want to running the apollo?

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12303] opened 2020-08-28 22:28 UTC
We've discussed [the script](https://github.com/ApolloAuto/apollo/blob/master/docker/setup_host/setup_host.sh) docker/setup_host/setup_host.sh [here](https://github.com/ApolloAuto/apollo/issues/12258). But I'm still somewhat confused on the functionality/capability of it. Especially, do we need to run it as a very beginning step each time when I want to start apollo?

Best regards,
HY

**Comment by storypku** [comment] 2020-08-28 23:13
> We've discussed [the script](https://github.com/ApolloAuto/apollo/blob/master/docker/setup_host/setup_host.sh) docker/setup_host/setup_host.sh [here](https://github.com/ApolloAuto/apollo/issues/12258). But I'm still somewhat confused on the functionality/capability of it. Especially, do we need to run it as a very beginning step each time when I want to start apollo?
> 
> Best regards,
> HY

Let's continue the discussion at #12258 . 

This issue is going to be closed as duplicate of that issue. Thanks.

**Closed by storypku** 2020-08-28 23:13 UTC
