### ISSUE TITLE
Low or 0 PointCloud frameratio on lgsvl

### ISSUE THREAD

**Issue by junyeonwon1** [ApolloAuto/apollo#14647] opened 2022-10-12 13:14 UTC
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5:0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
Hello. Thanks for providing such a great tool.
Now, I am playing Apollo on LGSVL.

Since I have a 1080ti GPU, I am also running the perception module as well.
And, I find out that obstacles are not showing up on dreamview. Hence, I execute cyber_monitor to check the status.
When the simulator starts, the frame ratio of PointCloud becomes 0 or slightly larger than 0. At the same time, LiDAR status in dreamview changes between ON and Fatal repeatedly. Therefore, an ego car cannot detect obstacles properly. Right before the simulation starts, the frame ratio is close to 10.

Do you have any idea why it happens?

Thank you for your help in advance.

**Comment by daohu527** [comment] 2022-10-14 01:39
I think you can close all modules in apollo, first confirm whether the sensor data is normal.
- open the bridge
- check the PointCloud topic is 10Hz

**Comment by joon5283** [comment] 2022-10-16 18:59
Thanks for your feedback.

I closed all modules in apollo (dreamview) and runs the simulation. Then, the frequency of the pointcloud topic is 10Hz.
Then, I run the simulator using lgsvl Python API ( setup_apollo) and it looks fine now.

Could you explain why closing modules change the result?

**Comment by daohu527** [comment] 2022-10-17 01:39
From your description, I can't confirm what kind of problem is, closing apollo module is to find the problem.

We need to limit where the problem is, so I suggest you try turning off the apollo module

**Closed as completed** 2022-10-20 15:36 UTC
