### ISSUE TITLE
在docker中运行bash apollo.sh build出错

### ISSUE THREAD

**Issue by 1624715047** [ApolloAuto/apollo#13651] opened 2021-04-01 06:37 UTC
**Describe the bug**

**To Reproduce**
1. bash docker/scripts/dev_start.sh
2. bash docker/scripts/dev_into.sh
3. bash apollo.sh build
4. gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
(06:27:12) INFO: Elapsed time: 119.304s, Critical Path: 42.82s
(06:27:13) INFO: 1919 processes: 448 remote cache hit, 1316 internal, 155 local.
(06:27:13) FAILED: Build did NOT complete successfully

**Expected behavior**
希望编译通过
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [ubuntu18.04] 
 - Browser [safari]

**Additional context**

**Comment by storypku** [comment] 2021-04-01 07:29
This is usually caused by temporal insufficient memory. 

I would suggest that you stop other memory consuming tasks on your host and try again.

You can tweak the following line in https://github.com/ApolloAuto/apollo/blob/master/scripts/apollo_build.sh to see if the problem persists.

```
local job_args="--jobs=$(nproc) --local_ram_resources=HOST_RAM*0.7"
```

**Comment by 1624715047** [comment] 2021-04-01 08:40
重启后编译继续报错：（执行 ./apollo.sh build_opt）
Execution platform: @local_config_platform//:host
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
(08:11:44) INFO: Elapsed time: 234.175s, Critical Path: 144.70s
(08:11:44) INFO: 444 processes: 39 remote cache hit, 234 internal, 171 local.
(08:11:44) FAILED: Build did NOT complete successfully
[lw@in-dev-docker:/apollo]$

**Comment by daohu527** [comment] 2021-04-01 15:08
It's the same problem, you can try to reduce parallel compilation tasks by `--jobs`, and you can limit the memory by `--local_ram_resources`. Also you can provide the number of CPU cores and memory size of the computer you compiled
```
local job_args="--jobs=4 --local_ram_resources=HOST_RAM*0.7"
```

**Comment by storypku** [comment] 2021-04-22 08:03
@1624715047 I hope that your issue was resolved already, and I am going to close this issue now. If you have other issues, please feel free to open another issue or reopen this one if the problem persists.

Thank you for using Apollo.

**Closed by storypku** 2021-04-22 08:03 UTC

**Comment by Srikar-Chaganti** [comment] 2023-09-14 17:28
@storypku Any idea where we have to define the local job args?
I face the same issue on apollo8 and ubuntu 22.04.
