### ISSUE TITLE
Question about localization simulation through dreamview

### ISSUE THREAD

**Issue by joon5283** [ApolloAuto/apollo#5790] opened 2018-09-23 00:17 UTC
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: ubuntu 16.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 2.5

### Steps to reproduce the issue:
Hello. Nowadays, I am doing Apollo simulation through the dreamview. And I have a question about dreamview system. My goal is running the localization module so below is my command.

bash scripts/bootstrap.sh start
bash scripts/localization.sh start

And I play new bag file which has no '/apollo/localization/pose' topic messages but others all exactly same with demo_2.0.bag file. In this case, I think that the car would move the same route with demo_2.0.bag file case. (Because I only filter /apollo/localization/pose topic) But, the car is running differently with demo_2.0.bag case when I play with loop function. Could you tell me this above situation is right? Or did I modify something wrongly?
Another problem is when I play bag file without /apollo/localization/pose topic, new /apollo/localization/pose topics are created when time is 27 / 34.895545. Why such situation happened...? 

In advance, thank you for helping me.

**Comment by unacao** [comment] 2018-09-26 00:03
Do you see any data update from the ros topic /apollo/localization/pose?

**Comment by joon5283** [comment] 2018-09-26 00:06
@unacao 
I cannot see any messages from the ros topic /apollo/localization/pose right after running the rosbag play.
And after almost 30s, /apollo/localization/pose topic messages are created.

**Comment by unacao** [comment] 2018-09-26 22:15
I tried to reproduce the problem and seems like there is no /apollo/localization/pose output? Assigning to localization related developers for a further look. @zhouyao4321

**Comment by zhouyao4321** [comment] 2018-09-27 02:00
Localization module needs to be initialized before it broadcasts localization results. In demo bag, there are some inputs for localization module. So it's possible that the localization module starts to work after 30 seconds. But the localization module may not work properly, since when circling playing bag, the end of bag is connected to beginning again, which may lead to undefined localization output.

**Comment by joon5283** [comment] 2018-09-27 04:44
@unacao 
Yes right. After filter /apollo/localization/pose messages and do ./scripts/localization.sh start and do rosbag. Then, you can see the problem.
@zhouyao4321 
Thank you! Then, is there any method to solve this problem? I just want to play bag file perfectly with localization module.

**Comment by natashadsouza** [comment] 2019-03-20 23:46
Closing this issue as it appears to be resolved. Thanks!

**Closed by natashadsouza** 2019-03-20 23:46 UTC
Labels: Module: Simulation & Dreamview, Type: Help wanted
