### ISSUE TITLE
apollo2.5 navigation use smooth.sh error

### ISSUE THREAD

**Issue by sadsearth** [ApolloAuto/apollo#5531] opened 2018-08-28 12:58 UTC
We use our car record data into bag according to apollo/docs/howto/how_to_use_apollo_2.5_navigation_mode.md, I can get the bag in /apollo/data/bag/,and use python viewer_raw.py can see the routing line what we record. But when I use bash smooth.sh ./path_xxxx.bag.txt 200.
No matter how I change 200 parameter, the terminal always shows as follows:

- **E0828 20:21:24.138556 11146 qp_spline_reference_line_smoother.cc:181] Add jointness constraint failed.**:
- **E0828 20:21:24.138702 11146 qp_spline_reference_line_smoother.cc:61] Add constraint for spline smoother failed**:
- **E0828 20:21:24.138715 11146 smoother_util.cc:91] smooth initial reference line failed**:
- **E0828 20:21:24.140245 11146 smoother_util.cc:228] Failed to smooth a the line**:

Even though after I run the bash smooth.sh ./path_xxxx.bag.txt 200 can get a path_xxxx.bag.txt.smoothed in local path, when I use python viewer_raw.py, it's empty. So I wonder how to solve this problem.Thanks for helping me!

**Comment by jilinzhou** [comment] 2018-08-28 18:27
Same issue: https://github.com/ApolloAuto/apollo/issues/4280

**Comment by natashadsouza** [comment] 2018-08-28 18:55
Closing this issue as it is a duplicate of #4280 
@sadsearth if you have additional questions, feel free to reopen this issue. 
Thanks!

**Closed by natashadsouza** 2018-08-28 18:55 UTC
Labels: Module: Planning, Type: Question
