### ISSUE TITLE
Why slow or seize that running apollo1.5 on arm ?

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#4185] opened 2018-05-16 02:08 UTC
Hello Apollo team ! 
     I have two problem to ask you. such as : 
     (1) I run the apollo 1.5 on arm, and find dreamview that is slow. so I use the top commond to watch the availability of cpu that is 40%，  could you tell me  why slow ? Thank you! PS: there is not gpu on the board of arm. 
     (2) I run the apollo 1.5 on arm, when open the gps or velodyne on the dreamview, the dreamview is stop, but "rosbag play -l  demo_1.5.bag" is not stop in terminal. so why to open the gps or velodyne on the dreamview, the dreamview is stop ? Thank you ! 
     best regards !

**Comment by vlin17** [comment] 2018-09-06 18:35
Hi @breakisx,

1) Dreamview depends on WebGL for 3D rendering. Please go to http://webglreport.com/?v=2 to make sure  WebGL 1 & 2 are supported; otherwise, dreamview can be slow. Given there's no gpu on the board of arm, it is most likely the cause of slowness. 

2) could you check if there's any core dump under /apollo/data/core or error log under /apollo/data/log?

**Comment by natashadsouza** [comment] 2019-03-15 01:17
Closing this issue as it appears to be resolved. Feel free to reopen it if you have additional questions. Thanks!

**Closed by natashadsouza** 2019-03-15 01:17 UTC
Labels: Module: Build, Module: Docker, Module: Simulation & Dreamview, Type: Help wanted, Type: Question
